import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
const blArmCreate: ToolDefinition = { id: "bl_armature_create", name: "Create Armature", description: "Create a new armature object", descriptionJa: "新しいアーマチュアオブジェクトを作成", category: "bl_armature", inputSchema: z.object({ name: z.string().default("Armature"), x: z.number().default(0), y: z.number().default(0), z: z.number().default(0) }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_create", p); return r ? { success: true, message: `Armature: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const blArmAddBone: ToolDefinition = { id: "bl_armature_add_bone", name: "Add Bone", description: "Add a bone to armature", descriptionJa: "アーマチュアにボーンを追加", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), headX: z.number().default(0), headY: z.number().default(0), headZ: z.number().default(0), tailX: z.number().default(0), tailY: z.number().default(0), tailZ: z.number().default(1) }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_add_bone", p); return r ? { success: true, message: `Bone added: ${p.boneName}`, data: r } : { success: false, message: "Failed" }; } };

const blArmDeleteBone: ToolDefinition = { id: "bl_armature_delete_bone", name: "Delete Bone", description: "Delete a bone from armature", descriptionJa: "アーマチュアからボーンを削除", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_delete_bone", p); return r ? { success: true, message: `Deleted: ${p.boneName}`, data: r } : { success: false, message: "Failed" }; } };

const blArmSetParentBone: ToolDefinition = { id: "bl_armature_set_parent_bone", name: "Set Bone Parent", description: "Set parent bone for a bone", descriptionJa: "ボーンの親ボーンを設定", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), parentBone: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_set_parent_bone", p); return r ? { success: true, message: `${p.boneName} parented to ${p.parentBone}`, data: r } : { success: false, message: "Failed" }; } };

const blArmWeightPaint: ToolDefinition = { id: "bl_armature_weight_paint", name: "Enter Weight Paint", description: "Enter weight paint mode for mesh-armature pair", descriptionJa: "メッシュ-アーマチュアペアのウェイトペイントモードに入る", category: "bl_armature", inputSchema: z.object({ mesh: z.string(), armature: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_weight_paint", p); return r ? { success: true, message: "Weight paint mode", data: r } : { success: false, message: "Failed" }; } };

const blArmAutoWeight: ToolDefinition = { id: "bl_armature_auto_weights", name: "Auto Weights", description: "Assign automatic weights from bones", descriptionJa: "ボーンから自動ウェイトを割り当て", category: "bl_armature", inputSchema: z.object({ mesh: z.string(), armature: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_auto_weights", p); return r ? { success: true, message: "Auto weights assigned", data: r } : { success: false, message: "Failed" }; } };

const blArmPoseMode: ToolDefinition = { id: "bl_armature_pose_mode", name: "Toggle Pose Mode", description: "Enter or exit pose mode", descriptionJa: "ポーズモードの切替", category: "bl_armature", inputSchema: z.object({ armature: z.string(), enter: z.boolean().default(true) }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_pose_mode", p); return r ? { success: true, message: p.enter ? "Pose mode" : "Object mode", data: r } : { success: false, message: "Failed" }; } };

const blArmAddConstraint: ToolDefinition = { id: "bl_armature_add_constraint", name: "Add Bone Constraint", description: "Add constraint to a pose bone", descriptionJa: "ポーズボーンにコンストレイントを追加", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), type: z.enum(["IK","COPY_LOCATION","COPY_ROTATION","TRACK_TO","LIMIT_ROTATION","DAMPED_TRACK"]).default("IK"), target: z.string().optional() }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_add_constraint", p); return r ? { success: true, message: `Constraint ${p.type} added to ${p.boneName}`, data: r } : { success: false, message: "Failed" }; } };

const blArmAddIK: ToolDefinition = { id: "bl_armature_add_ik", name: "Add IK Chain", description: "Add IK constraint with chain length", descriptionJa: "チェーン長さ付きIKコンストレイントを追加", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), target: z.string(), chainLength: z.number().default(0) }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_add_ik", p); return r ? { success: true, message: `IK on ${p.boneName}`, data: r } : { success: false, message: "Failed" }; } };

const blArmGetInfo: ToolDefinition = { id: "bl_armature_get_info", name: "Get Armature Info", description: "Get bone hierarchy and counts", descriptionJa: "ボーン階層と数を取得", category: "bl_armature", inputSchema: z.object({ armature: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_armature_get_info", p); return r ? { success: true, message: "Armature info retrieved", data: r } : { success: false, message: "Failed" }; } };

export const blArmatureTools: ToolDefinition[] = [ blArmCreate, blArmAddBone, blArmDeleteBone, blArmSetParentBone, blArmWeightPaint, blArmAutoWeight, blArmPoseMode, blArmAddConstraint, blArmAddIK, blArmGetInfo ];