import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const blArmCreate: ToolDefinition = { id: "bl_armature_create", name: "Create Armature", description: "Create a new armature object", descriptionJa: "新しいアーマチュアオブジェクトを作成", category: "bl_armature", inputSchema: z.object({ name: z.string().default("Armature"), x: z.number().default(0), y: z.number().default(0), z: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_create", p, { successMessage: (_, p) => `Armature: ${p.name}` }) } };

const blArmAddBone: ToolDefinition = { id: "bl_armature_add_bone", name: "Add Bone", description: "Add a bone to armature", descriptionJa: "アーマチュアにボーンを追加", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), headX: z.number().default(0), headY: z.number().default(0), headZ: z.number().default(0), tailX: z.number().default(0), tailY: z.number().default(0), tailZ: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_add_bone", p, { successMessage: (_, p) => `Bone added: ${p.boneName}` }) } };

const blArmDeleteBone: ToolDefinition = { id: "bl_armature_delete_bone", name: "Delete Bone", description: "Delete a bone from armature", descriptionJa: "アーマチュアからボーンを削除", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_delete_bone", p, { successMessage: (_, p) => `Deleted: ${p.boneName}` }) } };

const blArmSetParentBone: ToolDefinition = { id: "bl_armature_set_parent_bone", name: "Set Bone Parent", description: "Set parent bone for a bone", descriptionJa: "ボーンの親ボーンを設定", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), parentBone: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_set_parent_bone", p, { successMessage: (_, p) => `${p.boneName} parented to ${p.parentBone}` }) } };

const blArmWeightPaint: ToolDefinition = { id: "bl_armature_weight_paint", name: "Enter Weight Paint", description: "Enter weight paint mode for mesh-armature pair", descriptionJa: "メッシュ-アーマチュアペアのウェイトペイントモードに入る", category: "bl_armature", inputSchema: z.object({ mesh: z.string(), armature: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_weight_paint", p, { successMessage: "Weight paint mode" }) } };

const blArmAutoWeight: ToolDefinition = { id: "bl_armature_auto_weights", name: "Auto Weights", description: "Assign automatic weights from bones", descriptionJa: "ボーンから自動ウェイトを割り当て", category: "bl_armature", inputSchema: z.object({ mesh: z.string(), armature: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_auto_weights", p, { successMessage: "Auto weights assigned" }) } };

const blArmPoseMode: ToolDefinition = { id: "bl_armature_pose_mode", name: "Toggle Pose Mode", description: "Enter or exit pose mode", descriptionJa: "ポーズモードの切替", category: "bl_armature", inputSchema: z.object({ armature: z.string(), enter: z.boolean().default(true) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_pose_mode", p, { successMessage: (_, p) => (p.enter ? "Pose mode" : "Object mode") }) } };

const blArmAddConstraint: ToolDefinition = { id: "bl_armature_add_constraint", name: "Add Bone Constraint", description: "Add constraint to a pose bone", descriptionJa: "ポーズボーンにコンストレイントを追加", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), type: z.enum(["IK","COPY_LOCATION","COPY_ROTATION","TRACK_TO","LIMIT_ROTATION","DAMPED_TRACK"]).default("IK"), target: z.string().optional() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_add_constraint", p, { successMessage: (_, p) => `Constraint ${p.type} added to ${p.boneName}` }) } };

const blArmAddIK: ToolDefinition = { id: "bl_armature_add_ik", name: "Add IK Chain", description: "Add IK constraint with chain length", descriptionJa: "チェーン長さ付きIKコンストレイントを追加", category: "bl_armature", inputSchema: z.object({ armature: z.string(), boneName: z.string(), target: z.string(), chainLength: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_add_ik", p, { successMessage: (_, p) => `IK on ${p.boneName}` }) } };

const blArmGetInfo: ToolDefinition = { id: "bl_armature_get_info", name: "Get Armature Info", description: "Get bone hierarchy and counts", descriptionJa: "ボーン階層と数を取得", category: "bl_armature", inputSchema: z.object({ armature: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_armature_get_info", p, { successMessage: "Armature info retrieved" }) } };

export const blArmatureTools: ToolDefinition[] = [ blArmCreate, blArmAddBone, blArmDeleteBone, blArmSetParentBone, blArmWeightPaint, blArmAutoWeight, blArmPoseMode, blArmAddConstraint, blArmAddIK, blArmGetInfo ];