import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const blAnimInsertKey: ToolDefinition = { id: "bl_anim_insert_keyframe", name: "Insert Keyframe", description: "Insert keyframe on object property", descriptionJa: "オブジェクトプロパティにキーフレームを挿入", category: "bl_animation", inputSchema: z.object({ name: z.string(), frame: z.number(), dataPath: z.enum(["location","rotation_euler","scale"]).default("location") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_insert_keyframe", p, { successMessage: (_, p) => `Keyframe at frame ${p.frame}` }) } };

const blAnimDeleteKey: ToolDefinition = { id: "bl_anim_delete_keyframe", name: "Delete Keyframe", description: "Delete keyframe at frame", descriptionJa: "指定フレームのキーフレームを削除", category: "bl_animation", inputSchema: z.object({ name: z.string(), frame: z.number(), dataPath: z.enum(["location","rotation_euler","scale"]).default("location") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_delete_keyframe", p, { successMessage: (_, p) => `Keyframe deleted at ${p.frame}` }) } };

const blAnimCreateBone: ToolDefinition = { id: "bl_anim_create_bone", name: "Create Bone", description: "Add a bone to an armature", descriptionJa: "アーマチュアにボーンを追加", category: "bl_animation", inputSchema: z.object({ armature: z.string(), boneName: z.string(), headX: z.number().default(0), headY: z.number().default(0), headZ: z.number().default(0), tailX: z.number().default(0), tailY: z.number().default(0), tailZ: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_create_bone", p, { successMessage: (_, p) => `Bone created: ${p.boneName}` }) } };

const blAnimAddIK: ToolDefinition = { id: "bl_anim_add_ik", name: "Add IK Constraint", description: "Add inverse kinematics constraint to bone", descriptionJa: "ボーンにIKコンストレイントを追加", category: "bl_animation", inputSchema: z.object({ armature: z.string(), boneName: z.string(), target: z.string(), chainLength: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_add_ik", p, { successMessage: (_, p) => `IK added to ${p.boneName}` }) } };

const blAnimNLATrack: ToolDefinition = { id: "bl_anim_add_nla_track", name: "Add NLA Track", description: "Push action to NLA track", descriptionJa: "アクションをNLAトラックにプッシュ", category: "bl_animation", inputSchema: z.object({ name: z.string(), actionName: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_add_nla_track", p, { successMessage: (_, p) => `NLA track added: ${p.actionName}` }) } };

const blAnimCreateAction: ToolDefinition = { id: "bl_anim_create_action", name: "Create Action", description: "Create a new animation action", descriptionJa: "新しいアニメーションアクションを作成", category: "bl_animation", inputSchema: z.object({ actionName: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_create_action", p, { successMessage: (_, p) => `Action created: ${p.actionName}` }) } };

const blAnimPlay: ToolDefinition = { id: "bl_anim_play", name: "Play Animation", description: "Play or stop animation playback", descriptionJa: "アニメーション再生/停止", category: "bl_animation", inputSchema: z.object({ play: z.boolean().default(true) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_play", p, { successMessage: (_, p) => (p.play ? "Playing" : "Stopped") }) } };

const blAnimBake: ToolDefinition = { id: "bl_anim_bake", name: "Bake Animation", description: "Bake animation to keyframes", descriptionJa: "アニメーションをキーフレームにベイク", category: "bl_animation", inputSchema: z.object({ name: z.string(), startFrame: z.number().default(1), endFrame: z.number().default(250) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_bake", p, { successMessage: (_, p) => `Baked frames ${p.startFrame}-${p.endFrame}` }) } };

const blAnimSetFPS: ToolDefinition = { id: "bl_anim_set_fps", name: "Set FPS", description: "Set scene frame rate", descriptionJa: "シーンのフレームレートを設定", category: "bl_animation", inputSchema: z.object({ fps: z.number().default(24) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_set_fps", p, { successMessage: (_, p) => `FPS set to ${p.fps}` }) } };

const blAnimExport: ToolDefinition = { id: "bl_anim_export", name: "Export Animation", description: "Export animation to FBX/BVH", descriptionJa: "アニメーションをFBX/BVHにエクスポート", category: "bl_animation", inputSchema: z.object({ name: z.string(), format: z.enum(["FBX","BVH"]).default("FBX"), path: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_anim_export", p, { successMessage: (_, p) => `Exported as ${p.format}` }) } };

export const blAnimationTools: ToolDefinition[] = [ blAnimInsertKey, blAnimDeleteKey, blAnimCreateBone, blAnimAddIK, blAnimNLATrack, blAnimCreateAction, blAnimPlay, blAnimBake, blAnimSetFPS, blAnimExport ];