import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { blenderBridge } from "../bridge/blender-bridge";

export const blCharacterMaterialTools: ToolDefinition[] = [
  {
    id: "bl_char_set_skin_color",
    name: "Character: Set Skin Color",
    description: "Set skin color by RGB or preset (fair, light, medium, olive, tan, brown, dark_brown, dark). Affects base color and subsurface scattering.",
    descriptionJa: "肌色設定（RGB指定 or プリセット：色白・明るめ・中間・オリーブ・小麦・ブラウン・ダークブラウン・ダーク）。ベースカラーとSSSに反映",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      colorRgb: z.object({ r: z.number().min(0).max(1), g: z.number().min(0).max(1), b: z.number().min(0).max(1) }).optional().describe("Skin color RGB (0-1)"),
      preset: z.enum(["fair", "light", "medium", "olive", "tan", "brown", "dark_brown", "dark"]).optional().describe("Skin color preset"),
      subsurfaceStrength: z.number().min(0).max(1).optional().describe("Subsurface scattering strength (default 0.3)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_skin_color", params),
  },
  {
    id: "bl_char_set_skin_texture",
    name: "Character: Set Skin Texture",
    description: "Set skin texture overlay: smooth, freckles, pores, aged. Controls roughness map and detail normals.",
    descriptionJa: "肌質設定（なめらか・そばかす・毛穴・加齢）。ラフネスマップとディテールノーマルを制御",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      texture: z.enum(["smooth", "freckles", "pores", "aged", "rough", "baby_smooth"]).describe("Skin texture type"),
      intensity: z.number().min(0).max(1).optional().describe("Texture intensity (default 0.5)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_skin_texture", params),
  },
  {
    id: "bl_char_add_mole",
    name: "Character: Add Mole/Beauty Mark",
    description: "Add a mole or beauty mark at a specified face/body position with size control.",
    descriptionJa: "ほくろ追加（顔・体の指定位置にサイズ指定で配置）",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      position: z.enum(["left_cheek", "right_cheek", "under_left_eye", "under_right_eye", "upper_lip", "chin", "neck", "shoulder", "custom"]).describe("Mole position"),
      customUV: z.object({ u: z.number(), v: z.number() }).optional().describe("Custom UV position (if position is custom)"),
      size: z.number().min(0).max(1).optional().describe("Mole size (0=tiny, 1=large, default 0.2)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_add_mole", params),
  },
  {
    id: "bl_char_set_makeup",
    name: "Character: Set Makeup",
    description: "Apply makeup: eyeshadow color, blush, lip color, foundation, eyeliner. Each parameter is optional.",
    descriptionJa: "メイク設定（アイシャドウ色・チーク・リップ色・ファンデーション・アイライナー、各パラメータ任意）",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      eyeshadowColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Eyeshadow color RGB"),
      eyeshadowIntensity: z.number().min(0).max(1).optional().describe("Eyeshadow intensity"),
      blushColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Blush color RGB"),
      blushIntensity: z.number().min(0).max(1).optional().describe("Blush intensity"),
      lipColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Lip color RGB"),
      lipGloss: z.number().min(0).max(1).optional().describe("Lip gloss level"),
      eyeliner: z.number().min(0).max(1).optional().describe("Eyeliner thickness (0=none)"),
      foundation: z.number().min(0).max(1).optional().describe("Foundation coverage (0=none)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_makeup", params),
  },
  {
    id: "bl_char_set_eye_material",
    name: "Character: Set Eye Material",
    description: "Configure eye material: iris color, sclera color, iris detail, wetness/reflection, pupil dilation.",
    descriptionJa: "目のマテリアル設定（虹彩色・白目色・虹彩ディテール・潤み/反射・瞳孔拡張）",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      irisColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Iris color RGB"),
      scleraColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Sclera (white) color RGB"),
      irisDetail: z.number().min(0).max(1).optional().describe("Iris detail/complexity"),
      wetness: z.number().min(0).max(1).optional().describe("Eye wetness/reflection (default 0.7)"),
      pupilDilation: z.number().min(0).max(1).optional().describe("Pupil dilation (0=pinpoint, 1=dilated)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_eye_material", params),
  },
  {
    id: "bl_char_set_nail_color",
    name: "Character: Set Nail Color",
    description: "Set fingernail and toenail color with optional glitter and French tip style.",
    descriptionJa: "ネイルカラー設定（指・足の爪の色、グリッター、フレンチチップ対応）",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      color: z.object({ r: z.number(), g: z.number(), b: z.number() }).describe("Nail color RGB (0-1)"),
      glitter: z.number().min(0).max(1).optional().describe("Glitter amount (0=none, default 0)"),
      frenchTip: z.boolean().optional().describe("Enable French tip style (default false)"),
      tipColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("French tip color RGB"),
      target: z.enum(["fingers", "toes", "both"]).optional().describe("Apply to fingers, toes, or both (default both)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_nail_color", params),
  },
  {
    id: "bl_char_set_body_tattoo",
    name: "Character: Add Body Tattoo/Paint",
    description: "Add a tattoo or body paint decal at a specified body position with image path, size, rotation, and opacity.",
    descriptionJa: "タトゥー/ボディペイント追加（画像パス・体の位置・サイズ・回転・不透明度を指定）",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      imagePath: z.string().optional().describe("Tattoo image file path (PNG with alpha)"),
      preset: z.enum(["tribal", "floral", "dragon", "skull", "geometric", "text", "custom"]).optional().describe("Tattoo preset (if no imagePath)"),
      bodyPart: z.enum(["upper_arm_l", "upper_arm_r", "forearm_l", "forearm_r", "chest", "back", "neck", "ankle_l", "ankle_r", "thigh_l", "thigh_r", "face"]).describe("Body part for tattoo placement"),
      size: z.number().min(0).max(1).optional().describe("Tattoo size (default 0.3)"),
      rotation: z.number().optional().describe("Rotation in degrees (default 0)"),
      opacity: z.number().min(0).max(1).optional().describe("Opacity (default 1.0)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_body_tattoo", params),
  },
  {
    id: "bl_char_set_scar",
    name: "Character: Add Scar",
    description: "Add a scar with type (slash, burn, stitch), position, length, depth, and age (fresh to faded).",
    descriptionJa: "傷跡追加（種類：切り傷・火傷・縫合跡、位置・長さ・深さ・新旧度を指定）",
    category: "BL_CharacterMaterial",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      scarType: z.enum(["slash", "burn", "stitch", "puncture", "scratch"]).describe("Scar type"),
      bodyPart: z.enum(["face_left", "face_right", "forehead", "chest", "back", "arm_l", "arm_r", "leg_l", "leg_r", "hand_l", "hand_r"]).describe("Scar body position"),
      length: z.number().min(0).max(1).optional().describe("Scar length (0=small, 1=large, default 0.3)"),
      depth: z.number().min(0).max(1).optional().describe("Scar depth/visibility (0=shallow, 1=deep)"),
      age: z.enum(["fresh", "healing", "old", "faded"]).optional().describe("Scar age (default old)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_scar", params),
  },
];