import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { blenderBridge } from "../bridge/blender-bridge";

export const blCharacterFaceTools: ToolDefinition[] = [
  {
    id: "bl_char_set_face_outline",
    name: "Character: Set Face Outline",
    description: "Set face outline type (round, oval, square, inverted triangle, heart) with fine-tuning sliders.",
    descriptionJa: "輪郭タイプ設定（丸顔・卵型・四角・逆三角・ハート型）＋微調整スライダー",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      type: z.enum(["round", "oval", "square", "inverted_triangle", "heart"]).describe("Face outline type"),
      width: z.number().min(0).max(1).optional().describe("Face width fine-tune"),
      length: z.number().min(0).max(1).optional().describe("Face length fine-tune"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_face_outline", params),
  },
  {
    id: "bl_char_set_jaw",
    name: "Character: Set Jaw",
    description: "Adjust jaw length, width, and angle independently.",
    descriptionJa: "顎の長さ・幅・角度を個別調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      jawLength: z.number().min(0).max(1).optional().describe("Jaw length"),
      jawWidth: z.number().min(0).max(1).optional().describe("Jaw width"),
      jawAngle: z.number().min(0).max(1).optional().describe("Jaw angle (0=round, 1=sharp)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_jaw", params),
  },
  {
    id: "bl_char_set_cheekbone",
    name: "Character: Set Cheekbone",
    description: "Adjust cheekbone height and width.",
    descriptionJa: "頬骨の高さと幅を調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      cheekHeight: z.number().min(0).max(1).optional().describe("Cheekbone height"),
      cheekWidth: z.number().min(0).max(1).optional().describe("Cheekbone width"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_cheekbone", params),
  },
  {
    id: "bl_char_set_eye_shape",
    name: "Character: Set Eye Shape",
    description: "Adjust eye size, spacing, height position, and angle (upturned/downturned).",
    descriptionJa: "目の形状設定（サイズ・間隔・高さ・角度（つり目/たれ目））",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      eyeSize: z.number().min(0).max(1).optional().describe("Eye size (0=small, 1=large)"),
      eyeSpacing: z.number().min(0).max(1).optional().describe("Eye spacing (0=close, 1=wide)"),
      eyeHeight: z.number().min(0).max(1).optional().describe("Eye vertical position"),
      eyeAngle: z.number().min(-1).max(1).optional().describe("Eye angle (-1=downturned, 0=neutral, 1=upturned)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_eye_shape", params),
  },
  {
    id: "bl_char_set_eyelid",
    name: "Character: Set Eyelid",
    description: "Adjust double eyelid fold width and eyelid thickness.",
    descriptionJa: "二重幅とまぶたの厚さを調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      doubleFoldWidth: z.number().min(0).max(1).optional().describe("Double eyelid fold width (0=none/monolid, 1=deep)"),
      lidThickness: z.number().min(0).max(1).optional().describe("Eyelid thickness"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_eyelid", params),
  },
  {
    id: "bl_char_set_pupil",
    name: "Character: Set Pupil",
    description: "Set pupil/iris size, color (RGB or preset name), and iris pattern.",
    descriptionJa: "瞳設定（サイズ・色(RGB/プリセット名)・虹彩パターン）",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      pupilSize: z.number().min(0).max(1).optional().describe("Pupil/iris size"),
      irisColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Iris color RGB (0-1)"),
      irisPreset: z.enum(["brown", "blue", "green", "hazel", "gray", "amber", "red", "violet"]).optional().describe("Iris color preset"),
      irisPattern: z.enum(["default", "detailed", "anime", "cat", "heterochromia"]).optional().describe("Iris pattern type"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_pupil", params),
  },
  {
    id: "bl_char_set_eyebrow",
    name: "Character: Set Eyebrow",
    description: "Set eyebrow shape, thickness, angle, and vertical height.",
    descriptionJa: "眉の形・太さ・角度・高さを設定",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      shape: z.enum(["straight", "arched", "angled", "curved", "flat"]).optional().describe("Eyebrow shape"),
      thickness: z.number().min(0).max(1).optional().describe("Eyebrow thickness"),
      angle: z.number().min(-1).max(1).optional().describe("Eyebrow angle (-1=down, 1=up)"),
      height: z.number().min(0).max(1).optional().describe("Eyebrow vertical position"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_eyebrow", params),
  },
  {
    id: "bl_char_set_nose",
    name: "Character: Set Nose",
    description: "Adjust nose height, width, tip angle, and bridge width.",
    descriptionJa: "鼻の高さ・幅・先端角度・鼻梁幅を調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      noseHeight: z.number().min(0).max(1).optional().describe("Nose height/projection"),
      noseWidth: z.number().min(0).max(1).optional().describe("Nose width"),
      tipAngle: z.number().min(-1).max(1).optional().describe("Nose tip angle (-1=down, 1=up)"),
      bridgeWidth: z.number().min(0).max(1).optional().describe("Nose bridge width"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_nose", params),
  },
  {
    id: "bl_char_set_mouth",
    name: "Character: Set Mouth",
    description: "Adjust mouth width, lip thickness (upper/lower), and mouth corner height.",
    descriptionJa: "口の幅・唇の厚さ(上下)・口角の高さを調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      mouthWidth: z.number().min(0).max(1).optional().describe("Mouth width"),
      upperLipThickness: z.number().min(0).max(1).optional().describe("Upper lip thickness"),
      lowerLipThickness: z.number().min(0).max(1).optional().describe("Lower lip thickness"),
      cornerHeight: z.number().min(-1).max(1).optional().describe("Mouth corner (-1=frown, 0=neutral, 1=smile)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_mouth", params),
  },
  {
    id: "bl_char_set_ear",
    name: "Character: Set Ear",
    description: "Adjust ear size, angle (protruding), and elf-ear pointiness.",
    descriptionJa: "耳の設定（サイズ・角度（立ち耳度）・エルフ耳の尖り具合）",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      earSize: z.number().min(0).max(1).optional().describe("Ear size"),
      earAngle: z.number().min(0).max(1).optional().describe("Ear protrusion angle (0=flat, 1=protruding)"),
      elfPointiness: z.number().min(0).max(1).optional().describe("Elf ear pointiness (0=human, 1=full elf)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_ear", params),
  },
  {
    id: "bl_char_set_forehead",
    name: "Character: Set Forehead",
    description: "Adjust forehead height and roundness.",
    descriptionJa: "額の広さと丸みを調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      foreheadHeight: z.number().min(0).max(1).optional().describe("Forehead height"),
      foreheadRoundness: z.number().min(0).max(1).optional().describe("Forehead roundness"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_forehead", params),
  },
  {
    id: "bl_char_set_chin",
    name: "Character: Set Chin",
    description: "Adjust chin shape: cleft depth, pointiness, and protrusion.",
    descriptionJa: "顎先の形状設定（割れ顎の深さ・尖り具合・突出度）",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      cleftDepth: z.number().min(0).max(1).optional().describe("Chin cleft depth (0=none, 1=deep)"),
      pointiness: z.number().min(0).max(1).optional().describe("Chin pointiness (0=round, 1=pointed)"),
      protrusion: z.number().min(0).max(1).optional().describe("Chin protrusion"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_chin", params),
  },
  {
    id: "bl_char_set_temple",
    name: "Character: Set Temple Width",
    description: "Adjust temple (side of forehead) width.",
    descriptionJa: "こめかみ幅を調整",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      templeWidth: z.number().min(0).max(1).describe("Temple width (0=narrow, 1=wide)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_temple", params),
  },
  {
    id: "bl_char_set_nasolabial",
    name: "Character: Set Nasolabial Fold",
    description: "Adjust nasolabial fold (laugh line) depth. Useful for age variation.",
    descriptionJa: "ほうれい線の深さ調整（年齢表現に有用）",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      depth: z.number().min(0).max(1).describe("Nasolabial fold depth (0=none, 1=deep)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_nasolabial", params),
  },
  {
    id: "bl_char_set_face_preset",
    name: "Character: Apply Face Preset",
    description: "Apply a face preset that sets multiple face shape keys at once (anime, realistic, semi-realistic, chibi).",
    descriptionJa: "顔プリセット適用（アニメ系・リアル系・セミリアル系・ちび系を一括設定）",
    category: "BL_CharacterFace",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      preset: z.enum(["anime", "realistic", "semi_realistic", "chibi", "western_cartoon"]).describe("Face preset"),
      strength: z.number().min(0).max(1).optional().describe("Preset blend strength (default 1.0)"),
    }),
    handler: async (params) => blenderBridge.send("bl_char_set_face_preset", params),
  },
];