import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
export const blCharacterHairTools: ToolDefinition[] = [
  {
    id: "bl_char_set_hair_style",
    name: "Character: Set Hair Style",
    description: "Set base hair style from presets. Each style has adjustable sub-parameters.",
    descriptionJa: "ベースヘアスタイル設定（プリセットから選択、各スタイルにサブパラメータあり）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      style: z.enum(["straight_long", "straight_short", "straight_bob", "wavy_long", "wavy_medium", "curly_long", "curly_short", "afro", "ponytail", "twintail", "bun", "braids", "mohawk", "buzzcut", "undercut", "asymmetric", "hime_cut"]).describe("Hair style preset"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_style", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_length",
    name: "Character: Set Hair Length",
    description: "Set hair length in centimeters for front (bangs), side, and back independently. Fine control like trimming 1cm.",
    descriptionJa: "髪の長さをcm単位で設定（前髪・サイド・バックを個別指定。1cm単位の微調整可能）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      frontCm: z.number().min(0).max(150).optional().describe("Front (bangs) length in cm"),
      sideCm: z.number().min(0).max(150).optional().describe("Side hair length in cm"),
      backCm: z.number().min(0).max(150).optional().describe("Back hair length in cm"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_length", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_color",
    name: "Character: Set Hair Color",
    description: "Set main hair color by RGB values or preset name (ash, platinum_blonde, dark_brown, black, red, pink, silver, etc.).",
    descriptionJa: "髪のメインカラー設定（RGB指定 or プリセット名：アッシュ、プラチナブロンド、ダークブラウン、黒、赤、ピンク、シルバー等）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      colorRgb: z.object({ r: z.number().min(0).max(1), g: z.number().min(0).max(1), b: z.number().min(0).max(1) }).optional().describe("Hair color as RGB (0-1)"),
      preset: z.enum(["black", "dark_brown", "brown", "light_brown", "blonde", "platinum_blonde", "ash", "ash_gray", "ash_brown", "ash_blonde", "silver", "white", "red", "auburn", "ginger", "pink", "blue", "green", "purple", "lavender", "orange", "teal"]).optional().describe("Color preset name"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_color", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_gradient",
    name: "Character: Set Hair Gradient",
    description: "Set hair color gradient from root to tip. Supports ombre and balayage styles.",
    descriptionJa: "髪のグラデーション設定（根本色→毛先色、オンブレ・バレイヤージュ対応）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      rootColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).describe("Root color RGB (0-1)"),
      tipColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).describe("Tip color RGB (0-1)"),
      gradientPosition: z.number().min(0).max(1).optional().describe("Where gradient starts (0=root, 1=tip, default 0.5)"),
      style: z.enum(["ombre", "balayage", "dip_dye", "roots_only"]).optional().describe("Gradient style"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_gradient", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_highlight",
    name: "Character: Set Hair Highlight",
    description: "Add highlight/mesh streaks to hair with color, position, width, and count.",
    descriptionJa: "メッシュ/ハイライト追加（色・位置・幅・本数を指定）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      highlightColor: z.object({ r: z.number(), g: z.number(), b: z.number() }).describe("Highlight color RGB (0-1)"),
      position: z.enum(["front", "side_left", "side_right", "random", "frame"]).optional().describe("Highlight position"),
      width: z.number().min(0).max(1).optional().describe("Streak width (0=thin, 1=thick)"),
      count: z.number().min(1).max(20).optional().describe("Number of highlight streaks (default 3)"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_highlight", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_volume",
    name: "Character: Set Hair Volume",
    description: "Adjust overall hair volume/thickness. Affects how puffy or flat the hair appears.",
    descriptionJa: "髪のボリューム調整（ふわふわ〜ペタンコの制御）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      volume: z.number().min(0).max(1).describe("Hair volume (0=flat, 0.5=normal, 1=very fluffy)"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_volume", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_shine",
    name: "Character: Set Hair Shine",
    description: "Adjust hair shininess/glossiness. Controls specular and roughness of hair material.",
    descriptionJa: "髪のツヤ・光沢度調整（スペキュラー・ラフネスを制御）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      shine: z.number().min(0).max(1).describe("Shininess (0=matte, 0.5=normal, 1=glossy)"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_shine", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_physics",
    name: "Character: Set Hair Physics",
    description: "Configure hair physics parameters for VRChat PhysBone or VRM SpringBone: stiffness, gravity, wind influence, collision radius.",
    descriptionJa: "髪の揺れ物物理設定（PhysBone/SpringBone用：剛性・重力・風影響・コリジョン半径）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      stiffness: z.number().min(0).max(1).optional().describe("Stiffness (0=floppy, 1=rigid, default 0.3)"),
      gravity: z.number().min(0).max(1).optional().describe("Gravity influence (default 0.5)"),
      wind: z.number().min(0).max(1).optional().describe("Wind influence (default 0.2)"),
      collisionRadius: z.number().min(0).max(0.5).optional().describe("Collision radius in meters (default 0.05)"),
      damping: z.number().min(0).max(1).optional().describe("Damping (default 0.4)"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_physics", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_set_hair_part",
    name: "Character: Set Hair Part",
    description: "Set hair parting position and style (center, left, right, zigzag, none).",
    descriptionJa: "分け目の位置とスタイル設定（センター・左・右・ジグザグ・なし）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      partStyle: z.enum(["center", "left", "right", "zigzag", "none"]).describe("Parting style"),
      partOffset: z.number().min(-1).max(1).optional().describe("Fine offset (-1=far left, 0=center, 1=far right)"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_set_hair_part", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
  {
    id: "bl_char_add_hair_accessory",
    name: "Character: Add Hair Accessory",
    description: "Add a hair accessory (ribbon, hairpin, headband, flower, tiara, scrunchie) at a specified position.",
    descriptionJa: "髪飾り追加（リボン・ヘアピン・カチューシャ・花飾り・ティアラ・シュシュを指定位置に配置）",
    category: "BL_CharacterHair",
    inputSchema: z.object({
      objectName: z.string().optional().describe("Target character object name"),
      accessoryType: z.enum(["ribbon", "hairpin", "headband", "flower", "tiara", "scrunchie", "hat", "bow"]).describe("Accessory type"),
      position: z.enum(["top", "side_left", "side_right", "back", "bangs"]).optional().describe("Placement position (default top)"),
      color: z.object({ r: z.number(), g: z.number(), b: z.number() }).optional().describe("Accessory color RGB (0-1)"),
    }),
    handler: async (params) => { try { return await bridge.send("blender", "bl_char_add_hair_accessory", params); } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } },
  },
];