import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
const blGPCreate: ToolDefinition = { id: "bl_gp_create", name: "Create Grease Pencil", description: "Create a new Grease Pencil object", descriptionJa: "新しいグリースペンシルオブジェクトを作成", category: "bl_greasepencil", inputSchema: z.object({ name: z.string().default("GPencil") }), handler: async (p) => { const r = await bridge.send("blender", "GPCreate", p); return r ? { success: true, message: `GP created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const blGPAddLayer: ToolDefinition = { id: "bl_gp_add_layer", name: "Add GP Layer", description: "Add a layer to Grease Pencil object", descriptionJa: "グリースペンシルにレイヤーを追加", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), layerName: z.string().default("Layer") }), handler: async (p) => { const r = await bridge.send("blender", "GPAddLayer", p); return r ? { success: true, message: `Layer: ${p.layerName}`, data: r } : { success: false, message: "Failed" }; } };

const blGPSetBrush: ToolDefinition = { id: "bl_gp_set_brush", name: "Set GP Brush", description: "Set active Grease Pencil brush", descriptionJa: "アクティブGPブラシを設定", category: "bl_greasepencil", inputSchema: z.object({ brush: z.enum(["DRAW","FILL","ERASE","TINT"]).default("DRAW") }), handler: async (p) => { const r = await bridge.send("blender", "GPSetBrush", p); return r ? { success: true, message: `Brush: ${p.brush}`, data: r } : { success: false, message: "Failed" }; } };

const blGPSetColor: ToolDefinition = { id: "bl_gp_set_color", name: "Set GP Color", description: "Set Grease Pencil stroke color", descriptionJa: "GPストロークの色を設定", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), r: z.number().default(0), g: z.number().default(0), b: z.number().default(0), a: z.number().default(1) }), handler: async (p) => { const r = await bridge.send("blender", "GPSetColor", p); return r ? { success: true, message: "GP color set", data: r } : { success: false, message: "Failed" }; } };

const blGPSetLineWidth: ToolDefinition = { id: "bl_gp_set_line_width", name: "Set GP Line Width", description: "Set stroke line width", descriptionJa: "ストロークの線幅を設定", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), width: z.number().default(3) }), handler: async (p) => { const r = await bridge.send("blender", "GPSetLineWidth", p); return r ? { success: true, message: `Width: ${p.width}`, data: r } : { success: false, message: "Failed" }; } };

const blGPAddModifier: ToolDefinition = { id: "bl_gp_add_modifier", name: "Add GP Modifier", description: "Add modifier to Grease Pencil (Thickness/Noise/Tint/Smooth)", descriptionJa: "GPにモディファイアを追加", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), type: z.enum(["GP_THICK","GP_NOISE","GP_TINT","GP_SMOOTH"]).default("GP_SMOOTH") }), handler: async (p) => { const r = await bridge.send("blender", "GPAddModifier", p); return r ? { success: true, message: `GP modifier: ${p.type}`, data: r } : { success: false, message: "Failed" }; } };

const blGPAnimate: ToolDefinition = { id: "bl_gp_animate", name: "GP Animation Frame", description: "Add blank drawing frame for GP animation", descriptionJa: "GPアニメーション用の空白描画フレームを追加", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), frame: z.number().default(1) }), handler: async (p) => { const r = await bridge.send("blender", "GPAnimate", p); return r ? { success: true, message: `GP frame at ${p.frame}`, data: r } : { success: false, message: "Failed" }; } };

const blGPExport: ToolDefinition = { id: "bl_gp_export", name: "Export Grease Pencil", description: "Export GP to SVG or PDF", descriptionJa: "GPをSVGまたはPDFにエクスポート", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), format: z.enum(["SVG","PDF"]).default("SVG"), path: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "GPExport", p); return r ? { success: true, message: `Exported as ${p.format}`, data: r } : { success: false, message: "Failed" }; } };

export const blGreasePencilTools: ToolDefinition[] = [ blGPCreate, blGPAddLayer, blGPSetBrush, blGPSetColor, blGPSetLineWidth, blGPAddModifier, blGPAnimate, blGPExport ];