import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const blGPCreate: ToolDefinition = { id: "bl_gp_create", name: "Create Grease Pencil", description: "Create a new Grease Pencil object", descriptionJa: "新しいグリースペンシルオブジェクトを作成", category: "bl_greasepencil", inputSchema: z.object({ name: z.string().default("GPencil") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_create", p, { successMessage: (_, p) => `GP created: ${p.name}` }) } };

const blGPAddLayer: ToolDefinition = { id: "bl_gp_add_layer", name: "Add GP Layer", description: "Add a layer to Grease Pencil object", descriptionJa: "グリースペンシルにレイヤーを追加", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), layerName: z.string().default("Layer") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_add_layer", p, { successMessage: (_, p) => `Layer: ${p.layerName}` }) } };

const blGPSetBrush: ToolDefinition = { id: "bl_gp_set_brush", name: "Set GP Brush", description: "Set active Grease Pencil brush", descriptionJa: "アクティブGPブラシを設定", category: "bl_greasepencil", inputSchema: z.object({ brush: z.enum(["DRAW","FILL","ERASE","TINT"]).default("DRAW") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_set_brush", p, { successMessage: (_, p) => `Brush: ${p.brush}` }) } };

const blGPSetColor: ToolDefinition = { id: "bl_gp_set_color", name: "Set GP Color", description: "Set Grease Pencil stroke color", descriptionJa: "GPストロークの色を設定", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), r: z.number().default(0), g: z.number().default(0), b: z.number().default(0), a: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_set_color", p, { successMessage: "GP color set" }) } };

const blGPSetLineWidth: ToolDefinition = { id: "bl_gp_set_line_width", name: "Set GP Line Width", description: "Set stroke line width", descriptionJa: "ストロークの線幅を設定", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), width: z.number().default(3) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_set_line_width", p, { successMessage: (_, p) => `Width: ${p.width}` }) } };

const blGPAddModifier: ToolDefinition = { id: "bl_gp_add_modifier", name: "Add GP Modifier", description: "Add modifier to Grease Pencil (Thickness/Noise/Tint/Smooth)", descriptionJa: "GPにモディファイアを追加", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), type: z.enum(["GP_THICK","GP_NOISE","GP_TINT","GP_SMOOTH"]).default("GP_SMOOTH") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_add_modifier", p, { successMessage: (_, p) => `GP modifier: ${p.type}` }) } };

const blGPAnimate: ToolDefinition = { id: "bl_gp_animate", name: "GP Animation Frame", description: "Add blank drawing frame for GP animation", descriptionJa: "GPアニメーション用の空白描画フレームを追加", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), frame: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_animate", p, { successMessage: (_, p) => `GP frame at ${p.frame}` }) } };

const blGPExport: ToolDefinition = { id: "bl_gp_export", name: "Export Grease Pencil", description: "Export GP to SVG or PDF", descriptionJa: "GPをSVGまたはPDFにエクスポート", category: "bl_greasepencil", inputSchema: z.object({ name: z.string(), format: z.enum(["SVG","PDF"]).default("SVG"), path: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_gp_export", p, { successMessage: (_, p) => `Exported as ${p.format}` }) } };

export const blGreasePencilTools: ToolDefinition[] = [ blGPCreate, blGPAddLayer, blGPSetBrush, blGPSetColor, blGPSetLineWidth, blGPAddModifier, blGPAnimate, blGPExport ];