import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
const blModSubsurf: ToolDefinition = { id: "bl_mod_subsurf", name: "Add Subdivision Surface", description: "Add subdivision surface modifier", descriptionJa: "サブディビジョンサーフェスモディファイアを追加", category: "bl_modifier", inputSchema: z.object({ name: z.string(), levels: z.number().default(2), renderLevels: z.number().default(2) }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_subsurf", p); return r ? { success: true, message: `Subsurf added (level ${p.levels})`, data: r } : { success: false, message: "Failed" }; } };

const blModMirror: ToolDefinition = { id: "bl_mod_mirror", name: "Add Mirror", description: "Add mirror modifier", descriptionJa: "ミラーモディファイアを追加", category: "bl_modifier", inputSchema: z.object({ name: z.string(), axisX: z.boolean().default(true), axisY: z.boolean().default(false), axisZ: z.boolean().default(false) }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_mirror", p); return r ? { success: true, message: "Mirror added", data: r } : { success: false, message: "Failed" }; } };

const blModArray: ToolDefinition = { id: "bl_mod_array", name: "Add Array", description: "Add array modifier", descriptionJa: "配列モディファイアを追加", category: "bl_modifier", inputSchema: z.object({ name: z.string(), count: z.number().default(2), offsetX: z.number().default(1), offsetY: z.number().default(0), offsetZ: z.number().default(0) }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_array", p); return r ? { success: true, message: `Array added (count ${p.count})`, data: r } : { success: false, message: "Failed" }; } };

const blModBoolean: ToolDefinition = { id: "bl_mod_boolean", name: "Add Boolean", description: "Add boolean modifier (union/difference/intersect)", descriptionJa: "ブーリアンモディファイアを追加", category: "bl_modifier", inputSchema: z.object({ name: z.string(), target: z.string(), operation: z.enum(["UNION","DIFFERENCE","INTERSECT"]).default("DIFFERENCE") }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_boolean", p); return r ? { success: true, message: `Boolean ${p.operation}`, data: r } : { success: false, message: "Failed" }; } };

const blModSolidify: ToolDefinition = { id: "bl_mod_solidify", name: "Add Solidify", description: "Add solidify modifier for thickness", descriptionJa: "ソリディファイモディファイアを追加", category: "bl_modifier", inputSchema: z.object({ name: z.string(), thickness: z.number().default(0.01) }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_solidify", p); return r ? { success: true, message: `Solidify added (${p.thickness})`, data: r } : { success: false, message: "Failed" }; } };

const blModDecimate: ToolDefinition = { id: "bl_mod_decimate", name: "Add Decimate", description: "Add decimate modifier to reduce polycount", descriptionJa: "デシメートモディファイアでポリゴン数を削減", category: "bl_modifier", inputSchema: z.object({ name: z.string(), ratio: z.number().min(0).max(1).default(0.5) }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_decimate", p); return r ? { success: true, message: `Decimate ratio ${p.ratio}`, data: r } : { success: false, message: "Failed" }; } };

const blModWireframe: ToolDefinition = { id: "bl_mod_wireframe", name: "Add Wireframe", description: "Add wireframe modifier", descriptionJa: "ワイヤーフレームモディファイアを追加", category: "bl_modifier", inputSchema: z.object({ name: z.string(), thickness: z.number().default(0.02) }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_wireframe", p); return r ? { success: true, message: "Wireframe added", data: r } : { success: false, message: "Failed" }; } };

const blModApply: ToolDefinition = { id: "bl_mod_apply", name: "Apply Modifier", description: "Apply a modifier by name", descriptionJa: "モディファイアを適用", category: "bl_modifier", inputSchema: z.object({ name: z.string(), modifier: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_apply", p); return r ? { success: true, message: `Applied ${p.modifier}`, data: r } : { success: false, message: "Failed" }; } };

const blModRemove: ToolDefinition = { id: "bl_mod_remove", name: "Remove Modifier", description: "Remove a modifier by name", descriptionJa: "モディファイアを削除", category: "bl_modifier", inputSchema: z.object({ name: z.string(), modifier: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_remove", p); return r ? { success: true, message: `Removed ${p.modifier}`, data: r } : { success: false, message: "Failed" }; } };

const blModList: ToolDefinition = { id: "bl_mod_list", name: "List Modifiers", description: "List all modifiers on an object", descriptionJa: "オブジェクトの全モディファイアを一覧", category: "bl_modifier", inputSchema: z.object({ name: z.string() }), handler: async (p) => { const r = await bridge.send("blender", "bl_mod_list", p); return r ? { success: true, message: "Modifiers listed", data: r } : { success: false, message: "Failed" }; } };

export const blModifierTools: ToolDefinition[] = [ blModSubsurf, blModMirror, blModArray, blModBoolean, blModSolidify, blModDecimate, blModWireframe, blModApply, blModRemove, blModList ];