import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { blenderBridge } from "../bridge/blender-bridge";

const blMatCreate: ToolDefinition = { id: "bl_material_create", name: "Create Material", description: "Create a new material", descriptionJa: "新しいマテリアルを作成", category: "bl_material", inputSchema: z.object({ name: z.string().default("Material") }), handler: async (p) => { const r = await blenderBridge.send("MaterialCreate", p); return r ? { success: true, message: `Material created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const blMatSetColor: ToolDefinition = { id: "bl_material_set_color", name: "Set Base Color", description: "Set material base color", descriptionJa: "ベースカラーを設定", category: "bl_material", inputSchema: z.object({ name: z.string(), r: z.number().default(0.8), g: z.number().default(0.8), b: z.number().default(0.8), a: z.number().default(1) }), handler: async (p) => { const r = await blenderBridge.send("MaterialSetColor", p); return r ? { success: true, message: "Color set", data: r } : { success: false, message: "Failed" }; } };

const blMatSetMetallic: ToolDefinition = { id: "bl_material_set_metallic", name: "Set Metallic", description: "Set metallic value", descriptionJa: "メタリック値を設定", category: "bl_material", inputSchema: z.object({ name: z.string(), value: z.number().min(0).max(1).default(0) }), handler: async (p) => { const r = await blenderBridge.send("MaterialSetMetallic", p); return r ? { success: true, message: `Metallic: ${p.value}`, data: r } : { success: false, message: "Failed" }; } };

const blMatSetRoughness: ToolDefinition = { id: "bl_material_set_roughness", name: "Set Roughness", description: "Set roughness value", descriptionJa: "ラフネス値を設定", category: "bl_material", inputSchema: z.object({ name: z.string(), value: z.number().min(0).max(1).default(0.5) }), handler: async (p) => { const r = await blenderBridge.send("MaterialSetRoughness", p); return r ? { success: true, message: `Roughness: ${p.value}`, data: r } : { success: false, message: "Failed" }; } };

const blMatSetTexture: ToolDefinition = { id: "bl_material_set_texture", name: "Set Texture", description: "Set image texture on material", descriptionJa: "マテリアルにイメージテクスチャを設定", category: "bl_material", inputSchema: z.object({ name: z.string(), path: z.string() }), handler: async (p) => { const r = await blenderBridge.send("MaterialSetTexture", p); return r ? { success: true, message: "Texture set", data: r } : { success: false, message: "Failed" }; } };

const blMatAddNode: ToolDefinition = { id: "bl_material_add_node", name: "Add Shader Node", description: "Add a node to material node tree", descriptionJa: "マテリアルノードツリーにノードを追加", category: "bl_material", inputSchema: z.object({ name: z.string(), nodeType: z.string(), x: z.number().default(0), y: z.number().default(0) }), handler: async (p) => { const r = await blenderBridge.send("MaterialAddNode", p); return r ? { success: true, message: `Node added: ${p.nodeType}`, data: r } : { success: false, message: "Failed" }; } };

const blMatAssign: ToolDefinition = { id: "bl_material_assign", name: "Assign Material", description: "Assign material to object", descriptionJa: "オブジェクトにマテリアルを割り当て", category: "bl_material", inputSchema: z.object({ objectName: z.string(), materialName: z.string() }), handler: async (p) => { const r = await blenderBridge.send("MaterialAssign", p); return r ? { success: true, message: `${p.materialName} assigned to ${p.objectName}`, data: r } : { success: false, message: "Failed" }; } };

const blMatRemove: ToolDefinition = { id: "bl_material_remove", name: "Remove Material", description: "Remove material from object", descriptionJa: "オブジェクトからマテリアルを削除", category: "bl_material", inputSchema: z.object({ objectName: z.string(), materialName: z.string() }), handler: async (p) => { const r = await blenderBridge.send("MaterialRemove", p); return r ? { success: true, message: `${p.materialName} removed`, data: r } : { success: false, message: "Failed" }; } };

export const blMaterialTools: ToolDefinition[] = [ blMatCreate, blMatSetColor, blMatSetMetallic, blMatSetRoughness, blMatSetTexture, blMatAddNode, blMatAssign, blMatRemove ];