import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const blMatCreate: ToolDefinition = { id: "bl_material_create", name: "Create Material", description: "Create a new material", descriptionJa: "新しいマテリアルを作成", category: "bl_material", inputSchema: z.object({ name: z.string().default("Material") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_create", p, { successMessage: (_, p) => `Material created: ${p.name}` }) } };

const blMatSetColor: ToolDefinition = { id: "bl_material_set_color", name: "Set Base Color", description: "Set material base color", descriptionJa: "ベースカラーを設定", category: "bl_material", inputSchema: z.object({ name: z.string(), r: z.number().default(0.8), g: z.number().default(0.8), b: z.number().default(0.8), a: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_set_color", p, { successMessage: "Color set" }) } };

const blMatSetMetallic: ToolDefinition = { id: "bl_material_set_metallic", name: "Set Metallic", description: "Set metallic value", descriptionJa: "メタリック値を設定", category: "bl_material", inputSchema: z.object({ name: z.string(), value: z.number().min(0).max(1).default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_set_metallic", p, { successMessage: (_, p) => `Metallic: ${p.value}` }) } };

const blMatSetRoughness: ToolDefinition = { id: "bl_material_set_roughness", name: "Set Roughness", description: "Set roughness value", descriptionJa: "ラフネス値を設定", category: "bl_material", inputSchema: z.object({ name: z.string(), value: z.number().min(0).max(1).default(0.5) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_set_roughness", p, { successMessage: (_, p) => `Roughness: ${p.value}` }) } };

const blMatSetTexture: ToolDefinition = { id: "bl_material_set_texture", name: "Set Texture", description: "Set image texture on material", descriptionJa: "マテリアルにイメージテクスチャを設定", category: "bl_material", inputSchema: z.object({ name: z.string(), path: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_set_texture", p, { successMessage: "Texture set" }) } };

const blMatAddNode: ToolDefinition = { id: "bl_material_add_node", name: "Add Shader Node", description: "Add a node to material node tree", descriptionJa: "マテリアルノードツリーにノードを追加", category: "bl_material", inputSchema: z.object({ name: z.string(), nodeType: z.string(), x: z.number().default(0), y: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_add_node", p, { successMessage: (_, p) => `Node added: ${p.nodeType}` }) } };

const blMatAssign: ToolDefinition = { id: "bl_material_assign", name: "Assign Material", description: "Assign material to object", descriptionJa: "オブジェクトにマテリアルを割り当て", category: "bl_material", inputSchema: z.object({ objectName: z.string(), materialName: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_assign", p, { successMessage: (_, p) => `${p.materialName} assigned to ${p.objectName}` }) } };

const blMatRemove: ToolDefinition = { id: "bl_material_remove", name: "Remove Material", description: "Remove material from object", descriptionJa: "オブジェクトからマテリアルを削除", category: "bl_material", inputSchema: z.object({ objectName: z.string(), materialName: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_material_remove", p, { successMessage: (_, p) => `${p.materialName} removed` }) } };

export const blMaterialTools: ToolDefinition[] = [ blMatCreate, blMatSetColor, blMatSetMetallic, blMatSetRoughness, blMatSetTexture, blMatAddNode, blMatAssign, blMatRemove ];