import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
const blNodeAdd: ToolDefinition = { id: "bl_node_add", name: "Add Shader Node", description: "Add a node to shader node tree", descriptionJa: "シェーダーノードツリーにノードを追加", category: "bl_node", inputSchema: z.object({ material: z.string(), nodeType: z.string(), x: z.number().default(0), y: z.number().default(0) }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_add", p); return r ? { success: true, message: `Node added: ${p.nodeType}`, data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeConnect: ToolDefinition = { id: "bl_node_connect", name: "Connect Nodes", description: "Connect two node sockets", descriptionJa: "2つのノードソケットを接続", category: "bl_node", inputSchema: z.object({ material: z.string(), fromNode: z.string(), fromSocket: z.number().default(0), toNode: z.string(), toSocket: z.number().default(0) }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_connect", p); return r ? { success: true, message: "Nodes connected", data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeDelete: ToolDefinition = { id: "bl_node_delete", name: "Delete Node", description: "Delete a node from the tree", descriptionJa: "ノードツリーからノードを削除", category: "bl_node", inputSchema: z.object({ material: z.string(), nodeName: z.string() }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_delete", p); return r ? { success: true, message: `Deleted: ${p.nodeName}`, data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeCreateGroup: ToolDefinition = { id: "bl_node_create_group", name: "Create Node Group", description: "Create a reusable node group", descriptionJa: "再利用可能なノードグループを作成", category: "bl_node", inputSchema: z.object({ groupName: z.string() }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_create_group", p); return r ? { success: true, message: `Group: ${p.groupName}`, data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeSetValue: ToolDefinition = { id: "bl_node_set_value", name: "Set Node Value", description: "Set an input value on a node", descriptionJa: "ノードの入力値を設定", category: "bl_node", inputSchema: z.object({ material: z.string(), nodeName: z.string(), inputIndex: z.number().default(0), value: z.number() }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_set_value", p); return r ? { success: true, message: "Value set", data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeArrange: ToolDefinition = { id: "bl_node_arrange", name: "Arrange Nodes", description: "Auto-arrange nodes in the tree", descriptionJa: "ノードツリーのノードを自動配置", category: "bl_node", inputSchema: z.object({ material: z.string() }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_arrange", p); return r ? { success: true, message: "Nodes arranged", data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeAddMix: ToolDefinition = { id: "bl_node_add_mix", name: "Add Mix Node", description: "Add a Mix Shader or Mix RGB node", descriptionJa: "MixシェーダーまたはMix RGBノードを追加", category: "bl_node", inputSchema: z.object({ material: z.string(), mixType: z.enum(["SHADER","RGB"]).default("RGB"), x: z.number().default(0), y: z.number().default(0) }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_add_mix", p); return r ? { success: true, message: `Mix node added (${p.mixType})`, data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeAddTexCoord: ToolDefinition = { id: "bl_node_add_tex_coord", name: "Add Texture Coordinate", description: "Add Texture Coordinate node", descriptionJa: "テクスチャ座標ノードを追加", category: "bl_node", inputSchema: z.object({ material: z.string(), x: z.number().default(-400), y: z.number().default(0) }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_add_tex_coord", p); return r ? { success: true, message: "Tex Coord node added", data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeSetOutput: ToolDefinition = { id: "bl_node_set_output", name: "Set Output Node", description: "Configure the Material Output node target", descriptionJa: "マテリアル出力ノードのターゲットを設定", category: "bl_node", inputSchema: z.object({ material: z.string(), target: z.enum(["ALL","EEVEE","CYCLES"]).default("ALL") }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_set_output", p); return r ? { success: true, message: `Output target: ${p.target}`, data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

const blNodeList: ToolDefinition = { id: "bl_node_list", name: "List Nodes", description: "List all nodes in a material node tree", descriptionJa: "マテリアルノードツリーの全ノードを一覧", category: "bl_node", inputSchema: z.object({ material: z.string() }), handler: async (p) => { try { const r = await bridge.send("blender", "bl_node_list", p); return r ? { success: true, message: "Nodes listed", data: r } : { success: false, message: "Failed" }; } catch (error: any) { return { success: false, message: `Error: ${error.message}` }; } } };

export const blNodeTools: ToolDefinition[] = [ blNodeAdd, blNodeConnect, blNodeDelete, blNodeCreateGroup, blNodeSetValue, blNodeArrange, blNodeAddMix, blNodeAddTexCoord, blNodeSetOutput, blNodeList ];