import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const blParticleAdd: ToolDefinition = { id: "bl_particle_add", name: "Add Particle System", description: "Add emitter particle system", descriptionJa: "エミッターパーティクルシステムを追加", category: "bl_particle", inputSchema: z.object({ name: z.string(), count: z.number().default(1000) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_add", p, { successMessage: (_, p) => `Particles added (${p.count})` }) } };

const blParticleHair: ToolDefinition = { id: "bl_particle_add_hair", name: "Add Hair System", description: "Add hair particle system", descriptionJa: "ヘアーパーティクルシステムを追加", category: "bl_particle", inputSchema: z.object({ name: z.string(), count: z.number().default(500), length: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_add_hair", p, { successMessage: (_, p) => `Hair added (${p.count})` }) } };

const blParticleSetCount: ToolDefinition = { id: "bl_particle_set_count", name: "Set Emission Count", description: "Set number of emitted particles", descriptionJa: "放出パーティクル数を設定", category: "bl_particle", inputSchema: z.object({ name: z.string(), count: z.number() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_set_count", p, { successMessage: (_, p) => `Count: ${p.count}` }) } };

const blParticleSetVelocity: ToolDefinition = { id: "bl_particle_set_velocity", name: "Set Velocity", description: "Set particle initial velocity", descriptionJa: "パーティクルの初速を設定", category: "bl_particle", inputSchema: z.object({ name: z.string(), normal: z.number().default(1), random: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_set_velocity", p, { successMessage: "Velocity set" }) } };

const blParticleSetLifetime: ToolDefinition = { id: "bl_particle_set_lifetime", name: "Set Lifetime", description: "Set particle lifetime in frames", descriptionJa: "パーティクルの寿命をフレームで設定", category: "bl_particle", inputSchema: z.object({ name: z.string(), lifetime: z.number().default(50), random: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_set_lifetime", p, { successMessage: (_, p) => `Lifetime: ${p.lifetime}f` }) } };

const blParticleSetGravity: ToolDefinition = { id: "bl_particle_set_gravity", name: "Set Particle Gravity", description: "Set gravity effect on particles", descriptionJa: "パーティクルへの重力効果を設定", category: "bl_particle", inputSchema: z.object({ name: z.string(), factor: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_set_gravity", p, { successMessage: (_, p) => `Gravity factor: ${p.factor}` }) } };

const blParticleSetRender: ToolDefinition = { id: "bl_particle_set_render", name: "Set Render Type", description: "Set particle render type (Halo/Object/Collection/Path)", descriptionJa: "パーティクルのレンダータイプを設定", category: "bl_particle", inputSchema: z.object({ name: z.string(), renderType: z.enum(["HALO","OBJECT","COLLECTION","PATH","NONE"]).default("HALO") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_set_render", p, { successMessage: (_, p) => `Render: ${p.renderType}` }) } };

const blParticleRemove: ToolDefinition = { id: "bl_particle_remove", name: "Remove Particle System", description: "Remove particle system from object", descriptionJa: "オブジェクトからパーティクルシステムを削除", category: "bl_particle", inputSchema: z.object({ name: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_particle_remove", p, { successMessage: "Particles removed" }) } };

export const blParticleTools: ToolDefinition[] = [ blParticleAdd, blParticleHair, blParticleSetCount, blParticleSetVelocity, blParticleSetLifetime, blParticleSetGravity, blParticleSetRender, blParticleRemove ];