import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const blRenderSetEngine: ToolDefinition = { id: "bl_render_set_engine", name: "Set Render Engine", description: "Set render engine (Cycles/Eevee/Workbench)", descriptionJa: "レンダーエンジンを設定", category: "bl_render", inputSchema: z.object({ engine: z.enum(["CYCLES","BLENDER_EEVEE_NEXT","BLENDER_WORKBENCH"]).default("CYCLES") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_set_engine", p, { successMessage: (_, p) => `Engine: ${p.engine}` }) } };

const blRenderSetResolution: ToolDefinition = { id: "bl_render_set_resolution", name: "Set Resolution", description: "Set render resolution", descriptionJa: "レンダー解像度を設定", category: "bl_render", inputSchema: z.object({ x: z.number().default(1920), y: z.number().default(1080), percentage: z.number().default(100) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_set_resolution", p, { successMessage: (_, p) => `Resolution: ${p.x}x${p.y} (${p.percentage}%)` }) } };

const blRenderSetSamples: ToolDefinition = { id: "bl_render_set_samples", name: "Set Samples", description: "Set render sample count", descriptionJa: "レンダーサンプル数を設定", category: "bl_render", inputSchema: z.object({ samples: z.number().default(128), denoising: z.boolean().default(true) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_set_samples", p, { successMessage: (_, p) => `Samples: ${p.samples}` }) } };

const blRenderSetOutput: ToolDefinition = { id: "bl_render_set_output", name: "Set Output Path", description: "Set render output file path and format", descriptionJa: "レンダー出力パスとフォーマットを設定", category: "bl_render", inputSchema: z.object({ path: z.string(), format: z.enum(["PNG","JPEG","OPEN_EXR","FFMPEG"]).default("PNG") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_set_output", p, { successMessage: (_, p) => `Output: ${p.path} (${p.format})` }) } };

const blRenderExecute: ToolDefinition = { id: "bl_render_execute", name: "Render Image", description: "Render current frame", descriptionJa: "現在のフレームをレンダリング", category: "bl_render", inputSchema: z.object({ animation: z.boolean().default(false) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_execute", p, { successMessage: (_, p) => (p.animation ? "Animation rendering" : "Frame rendered") }) } };

const blRenderDenoise: ToolDefinition = { id: "bl_render_set_denoise", name: "Set Denoiser", description: "Configure denoiser settings", descriptionJa: "デノイザー設定を構成", category: "bl_render", inputSchema: z.object({ enable: z.boolean().default(true), denoiser: z.enum(["OPENIMAGEDENOISE","OPTIX"]).default("OPENIMAGEDENOISE") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_set_denoise", p, { successMessage: (_, p) => `Denoiser: ${p.denoiser} (${p.enable ? "on" : "off"})` }) } };

const blRenderColorMgmt: ToolDefinition = { id: "bl_render_color_management", name: "Set Color Management", description: "Set view transform and look", descriptionJa: "ビュー変換とルックを設定", category: "bl_render", inputSchema: z.object({ viewTransform: z.enum(["Standard","Filmic","AgX","Raw"]).default("Filmic"), look: z.string().default("None") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_color_management", p, { successMessage: (_, p) => `View: ${p.viewTransform}` }) } };

const blRenderAOV: ToolDefinition = { id: "bl_render_add_aov", name: "Add AOV Pass", description: "Add render pass (AO, Normal, Depth, etc.)", descriptionJa: "レンダーパスを追加（AO, Normal, Depth等）", category: "bl_render", inputSchema: z.object({ pass: z.enum(["AO","NORMAL","Z","MIST","SHADOW","EMIT","ENVIRONMENT","DIFFUSE_COLOR","GLOSSY_COLOR"]).default("AO") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_add_aov", p, { successMessage: (_, p) => `Pass added: ${p.pass}` }) } };

const blRenderCompositor: ToolDefinition = { id: "bl_render_toggle_compositor", name: "Toggle Compositor", description: "Enable or disable compositor", descriptionJa: "コンポジターの有効/無効を切替", category: "bl_render", inputSchema: z.object({ enable: z.boolean().default(true) }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_toggle_compositor", p, { successMessage: (_, p) => `Compositor ${p.enable ? "on" : "off"}` }) } };

const blRenderViewLayer: ToolDefinition = { id: "bl_render_add_view_layer", name: "Add View Layer", description: "Add a new view layer", descriptionJa: "新しいビューレイヤーを追加", category: "bl_render", inputSchema: z.object({ layerName: z.string().default("ViewLayer") }), handler: async (p) => { return bridgeSendAsToolResult("blender", "bl_render_add_view_layer", p, { successMessage: (_, p) => `View layer: ${p.layerName}` }) } };

export const blRenderTools: ToolDefinition[] = [ blRenderSetEngine, blRenderSetResolution, blRenderSetSamples, blRenderSetOutput, blRenderExecute, blRenderDenoise, blRenderColorMgmt, blRenderAOV, blRenderCompositor, blRenderViewLayer ];