import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { blenderBridge } from "../bridge/blender-bridge";

const blRenderSetEngine: ToolDefinition = { id: "bl_render_set_engine", name: "Set Render Engine", description: "Set render engine (Cycles/Eevee/Workbench)", descriptionJa: "レンダーエンジンを設定", category: "bl_render", inputSchema: z.object({ engine: z.enum(["CYCLES","BLENDER_EEVEE_NEXT","BLENDER_WORKBENCH"]).default("CYCLES") }), handler: async (p) => { const r = await blenderBridge.send("RenderSetEngine", p); return r ? { success: true, message: `Engine: ${p.engine}`, data: r } : { success: false, message: "Failed" }; } };

const blRenderSetResolution: ToolDefinition = { id: "bl_render_set_resolution", name: "Set Resolution", description: "Set render resolution", descriptionJa: "レンダー解像度を設定", category: "bl_render", inputSchema: z.object({ x: z.number().default(1920), y: z.number().default(1080), percentage: z.number().default(100) }), handler: async (p) => { const r = await blenderBridge.send("RenderSetResolution", p); return r ? { success: true, message: `Resolution: ${p.x}x${p.y} (${p.percentage}%)`, data: r } : { success: false, message: "Failed" }; } };

const blRenderSetSamples: ToolDefinition = { id: "bl_render_set_samples", name: "Set Samples", description: "Set render sample count", descriptionJa: "レンダーサンプル数を設定", category: "bl_render", inputSchema: z.object({ samples: z.number().default(128), denoising: z.boolean().default(true) }), handler: async (p) => { const r = await blenderBridge.send("RenderSetSamples", p); return r ? { success: true, message: `Samples: ${p.samples}`, data: r } : { success: false, message: "Failed" }; } };

const blRenderSetOutput: ToolDefinition = { id: "bl_render_set_output", name: "Set Output Path", description: "Set render output file path and format", descriptionJa: "レンダー出力パスとフォーマットを設定", category: "bl_render", inputSchema: z.object({ path: z.string(), format: z.enum(["PNG","JPEG","OPEN_EXR","FFMPEG"]).default("PNG") }), handler: async (p) => { const r = await blenderBridge.send("RenderSetOutput", p); return r ? { success: true, message: `Output: ${p.path} (${p.format})`, data: r } : { success: false, message: "Failed" }; } };

const blRenderExecute: ToolDefinition = { id: "bl_render_execute", name: "Render Image", description: "Render current frame", descriptionJa: "現在のフレームをレンダリング", category: "bl_render", inputSchema: z.object({ animation: z.boolean().default(false) }), handler: async (p) => { const r = await blenderBridge.send("RenderExecute", p); return r ? { success: true, message: p.animation ? "Animation rendering" : "Frame rendered", data: r } : { success: false, message: "Failed" }; } };

const blRenderDenoise: ToolDefinition = { id: "bl_render_set_denoise", name: "Set Denoiser", description: "Configure denoiser settings", descriptionJa: "デノイザー設定を構成", category: "bl_render", inputSchema: z.object({ enable: z.boolean().default(true), denoiser: z.enum(["OPENIMAGEDENOISE","OPTIX"]).default("OPENIMAGEDENOISE") }), handler: async (p) => { const r = await blenderBridge.send("RenderSetDenoise", p); return r ? { success: true, message: `Denoiser: ${p.denoiser} (${p.enable ? "on" : "off"})`, data: r } : { success: false, message: "Failed" }; } };

const blRenderColorMgmt: ToolDefinition = { id: "bl_render_color_management", name: "Set Color Management", description: "Set view transform and look", descriptionJa: "ビュー変換とルックを設定", category: "bl_render", inputSchema: z.object({ viewTransform: z.enum(["Standard","Filmic","AgX","Raw"]).default("Filmic"), look: z.string().default("None") }), handler: async (p) => { const r = await blenderBridge.send("RenderColorManagement", p); return r ? { success: true, message: `View: ${p.viewTransform}`, data: r } : { success: false, message: "Failed" }; } };

const blRenderAOV: ToolDefinition = { id: "bl_render_add_aov", name: "Add AOV Pass", description: "Add render pass (AO, Normal, Depth, etc.)", descriptionJa: "レンダーパスを追加（AO, Normal, Depth等）", category: "bl_render", inputSchema: z.object({ pass: z.enum(["AO","NORMAL","Z","MIST","SHADOW","EMIT","ENVIRONMENT","DIFFUSE_COLOR","GLOSSY_COLOR"]).default("AO") }), handler: async (p) => { const r = await blenderBridge.send("RenderAddAOV", p); return r ? { success: true, message: `Pass added: ${p.pass}`, data: r } : { success: false, message: "Failed" }; } };

const blRenderCompositor: ToolDefinition = { id: "bl_render_toggle_compositor", name: "Toggle Compositor", description: "Enable or disable compositor", descriptionJa: "コンポジターの有効/無効を切替", category: "bl_render", inputSchema: z.object({ enable: z.boolean().default(true) }), handler: async (p) => { const r = await blenderBridge.send("RenderToggleCompositor", p); return r ? { success: true, message: `Compositor ${p.enable ? "on" : "off"}`, data: r } : { success: false, message: "Failed" }; } };

const blRenderViewLayer: ToolDefinition = { id: "bl_render_add_view_layer", name: "Add View Layer", description: "Add a new view layer", descriptionJa: "新しいビューレイヤーを追加", category: "bl_render", inputSchema: z.object({ layerName: z.string().default("ViewLayer") }), handler: async (p) => { const r = await blenderBridge.send("RenderAddViewLayer", p); return r ? { success: true, message: `View layer: ${p.layerName}`, data: r } : { success: false, message: "Failed" }; } };

export const blRenderTools: ToolDefinition[] = [ blRenderSetEngine, blRenderSetResolution, blRenderSetSamples, blRenderSetOutput, blRenderExecute, blRenderDenoise, blRenderColorMgmt, blRenderAOV, blRenderCompositor, blRenderViewLayer ];