import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { blenderBridge } from "../bridge/blender-bridge";

const blSceneList: ToolDefinition = { id: "bl_scene_list", name: "List Scenes", description: "List all scenes in the file", descriptionJa: "ファイル内の全シーンを一覧", category: "bl_scene", inputSchema: z.object({}), handler: async (p) => { const r = await blenderBridge.send("SceneList", p); return r ? { success: true, message: "Scenes listed", data: r } : { success: false, message: "Failed" }; } };

const blSceneCreate: ToolDefinition = { id: "bl_scene_create", name: "Create Scene", description: "Create a new scene", descriptionJa: "新しいシーンを作成", category: "bl_scene", inputSchema: z.object({ name: z.string().default("Scene") }), handler: async (p) => { const r = await blenderBridge.send("SceneCreate", p); return r ? { success: true, message: `Scene created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const blSceneDelete: ToolDefinition = { id: "bl_scene_delete", name: "Delete Scene", description: "Delete a scene by name", descriptionJa: "名前でシーンを削除", category: "bl_scene", inputSchema: z.object({ name: z.string() }), handler: async (p) => { const r = await blenderBridge.send("SceneDelete", p); return r ? { success: true, message: `Scene deleted: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const blSceneSetWorld: ToolDefinition = { id: "bl_scene_set_world", name: "Set World", description: "Set world background (HDRI or color)", descriptionJa: "ワールド背景を設定（HDRIまたは色）", category: "bl_scene", inputSchema: z.object({ hdriPath: z.string().optional(), r: z.number().default(0.05), g: z.number().default(0.05), b: z.number().default(0.05), strength: z.number().default(1) }), handler: async (p) => { const r = await blenderBridge.send("SceneSetWorld", p); return r ? { success: true, message: "World set", data: r } : { success: false, message: "Failed" }; } };

const blSceneSetUnits: ToolDefinition = { id: "bl_scene_set_units", name: "Set Units", description: "Set scene unit system and scale", descriptionJa: "シーンの単位系とスケールを設定", category: "bl_scene", inputSchema: z.object({ system: z.enum(["METRIC","IMPERIAL","NONE"]).default("METRIC"), scale: z.number().default(1) }), handler: async (p) => { const r = await blenderBridge.send("SceneSetUnits", p); return r ? { success: true, message: `Units: ${p.system}`, data: r } : { success: false, message: "Failed" }; } };

const blSceneSetFrameRange: ToolDefinition = { id: "bl_scene_set_frame_range", name: "Set Frame Range", description: "Set start and end frame", descriptionJa: "開始・終了フレームを設定", category: "bl_scene", inputSchema: z.object({ start: z.number().default(1), end: z.number().default(250) }), handler: async (p) => { const r = await blenderBridge.send("SceneSetFrameRange", p); return r ? { success: true, message: `Frames: ${p.start}-${p.end}`, data: r } : { success: false, message: "Failed" }; } };

const blSceneCreateCollection: ToolDefinition = { id: "bl_scene_create_collection", name: "Create Collection", description: "Create a new collection", descriptionJa: "新しいコレクションを作成", category: "bl_scene", inputSchema: z.object({ name: z.string() }), handler: async (p) => { const r = await blenderBridge.send("SceneCreateCollection", p); return r ? { success: true, message: `Collection: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const blSceneMoveToCollection: ToolDefinition = { id: "bl_scene_move_to_collection", name: "Move to Collection", description: "Move object to a collection", descriptionJa: "オブジェクトをコレクションに移動", category: "bl_scene", inputSchema: z.object({ objectName: z.string(), collectionName: z.string() }), handler: async (p) => { const r = await blenderBridge.send("SceneMoveToCollection", p); return r ? { success: true, message: `${p.objectName} moved to ${p.collectionName}`, data: r } : { success: false, message: "Failed" }; } };

export const blSceneTools: ToolDefinition[] = [ blSceneList, blSceneCreate, blSceneDelete, blSceneSetWorld, blSceneSetUnits, blSceneSetFrameRange, blSceneCreateCollection, blSceneMoveToCollection ];