import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const ueAnimImport: ToolDefinition = { id: "ue_anim_import", name: "Import Animation", description: "Import animation from FBX file", descriptionJa: "FBXファイルからアニメーションをインポート", category: "ue_animation", inputSchema: z.object({ filePath: z.string(), skeletonPath: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AnimImport", p, { successMessage: "Animation imported" }) } };

const ueAnimPlay: ToolDefinition = { id: "ue_anim_play", name: "Play Animation", description: "Play an animation montage on an actor", descriptionJa: "アクターでアニメーションモンタージュを再生", category: "ue_animation", inputSchema: z.object({ actorName: z.string(), montagePath: z.string(), playRate: z.number().default(1) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AnimPlay", p, { successMessage: (_, p) => `Playing on ${p.actorName}` }) } };

const ueAnimBlendspace: ToolDefinition = { id: "ue_anim_create_blendspace", name: "Create Blend Space", description: "Create a 1D or 2D blend space", descriptionJa: "1Dまたは2Dブレンドスペースを作成", category: "ue_animation", inputSchema: z.object({ name: z.string(), type: z.enum(["1D","2D"]).default("2D"), path: z.string().default("/Game/Animations") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AnimBlendspace", p, { successMessage: (_, p) => `Blend space created: ${p.name}` }) } };

const ueAnimMontageCreate: ToolDefinition = { id: "ue_anim_create_montage", name: "Create Montage", description: "Create an animation montage from clips", descriptionJa: "クリップからアニメーションモンタージュを作成", category: "ue_animation", inputSchema: z.object({ name: z.string(), animPath: z.string(), path: z.string().default("/Game/Animations") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AnimMontageCreate", p, { successMessage: (_, p) => `Montage created: ${p.name}` }) } };

const ueAnimSetBp: ToolDefinition = { id: "ue_anim_set_bp", name: "Set Anim Blueprint", description: "Assign an Animation Blueprint to a skeletal mesh", descriptionJa: "スケルタルメッシュにAnimation Blueprintを割り当て", category: "ue_animation", inputSchema: z.object({ actorName: z.string(), animBpPath: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AnimSetBp", p, { successMessage: (_, p) => `Anim BP set on ${p.actorName}` }) } };

const ueAnimRetarget: ToolDefinition = { id: "ue_anim_retarget", name: "Retarget Animation", description: "Retarget animation to a different skeleton", descriptionJa: "アニメーションを別のスケルトンにリターゲット", category: "ue_animation", inputSchema: z.object({ animPath: z.string(), targetSkeletonPath: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AnimRetarget", p, { successMessage: "Animation retargeted" }) } };

export const ueAnimationTools: ToolDefinition[] = [ ueAnimImport, ueAnimPlay, ueAnimBlendspace, ueAnimMontageCreate, ueAnimSetBp, ueAnimRetarget ];