import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const ueAiCreateBT: ToolDefinition = { id: "ue_ai_create_bt", name: "Create Behavior Tree", description: "Create a new Behavior Tree asset", descriptionJa: "新しいBehavior Treeアセットを作成", category: "ue_ai", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/AI") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiCreateBT", p, { successMessage: (_, p) => `BT created: ${p.name}` }) } };

const ueAiCreateBB: ToolDefinition = { id: "ue_ai_create_bb", name: "Create Blackboard", description: "Create a Blackboard data asset", descriptionJa: "Blackboardデータアセットを作成", category: "ue_ai", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/AI") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiCreateBB", p, { successMessage: (_, p) => `Blackboard created: ${p.name}` }) } };

const ueAiAddBBKey: ToolDefinition = { id: "ue_ai_add_bb_key", name: "Add Blackboard Key", description: "Add a key to a Blackboard asset", descriptionJa: "Blackboardアセットにキーを追加", category: "ue_ai", inputSchema: z.object({ bbName: z.string(), keyName: z.string(), keyType: z.enum(["Bool","Int","Float","String","Vector","Object","Enum","Class"]).default("Object") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiAddBBKey", p, { successMessage: (_, p) => `Key ${p.keyName} added` }) } };

const ueAiAddBTTask: ToolDefinition = { id: "ue_ai_add_bt_task", name: "Add BT Task", description: "Add a task node to a Behavior Tree", descriptionJa: "Behavior Treeにタスクノードを追加", category: "ue_ai", inputSchema: z.object({ btName: z.string(), taskType: z.string(), parentNode: z.string().optional() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiAddBTTask", p, { successMessage: (_, p) => `Task ${p.taskType} added` }) } };

const ueAiAddBTDecorator: ToolDefinition = { id: "ue_ai_add_bt_decorator", name: "Add BT Decorator", description: "Add a decorator to a Behavior Tree node", descriptionJa: "Behavior Treeノードにデコレーターを追加", category: "ue_ai", inputSchema: z.object({ btName: z.string(), decoratorType: z.string(), targetNode: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiAddBTDecorator", p, { successMessage: (_, p) => `Decorator ${p.decoratorType} added` }) } };

const ueAiSetController: ToolDefinition = { id: "ue_ai_set_controller", name: "Set AI Controller", description: "Assign an AI Controller class to a pawn", descriptionJa: "PawnにAI Controllerクラスを割り当て", category: "ue_ai", inputSchema: z.object({ actorName: z.string(), controllerClass: z.string().default("AIController") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiSetController", p, { successMessage: (_, p) => `AI Controller set on ${p.actorName}` }) } };

const ueAiRunBT: ToolDefinition = { id: "ue_ai_run_bt", name: "Run Behavior Tree", description: "Start running a Behavior Tree on an AI controller", descriptionJa: "AIコントローラーでBehavior Treeを実行開始", category: "ue_ai", inputSchema: z.object({ actorName: z.string(), btPath: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiRunBT", p, { successMessage: (_, p) => `BT running on ${p.actorName}` }) } };

const ueAiAddEqs: ToolDefinition = { id: "ue_ai_add_eqs", name: "Create EQS Query", description: "Create an Environment Query System query", descriptionJa: "Environment Query System (EQS) クエリを作成", category: "ue_ai", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/AI"), generatorType: z.enum(["Grid","Circle","OnCircle","Cone","Donut"]).default("Grid") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "AiAddEqs", p, { successMessage: (_, p) => `EQS created: ${p.name}` }) } };

export const ueAiTools: ToolDefinition[] = [ ueAiCreateBT, ueAiCreateBB, ueAiAddBBKey, ueAiAddBTTask, ueAiAddBTDecorator, ueAiSetController, ueAiRunBT, ueAiAddEqs ];