import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { unrealBridge } from "../bridge/unreal-bridge";

const ueAiCreateBT: ToolDefinition = { id: "ue_ai_create_bt", name: "Create Behavior Tree", description: "Create a new Behavior Tree asset", descriptionJa: "新しいBehavior Treeアセットを作成", category: "ue_ai", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/AI") }), handler: async (p) => { const r = await unrealBridge.send("AiCreateBT", p); return r ? { success: true, message: `BT created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const ueAiCreateBB: ToolDefinition = { id: "ue_ai_create_bb", name: "Create Blackboard", description: "Create a Blackboard data asset", descriptionJa: "Blackboardデータアセットを作成", category: "ue_ai", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/AI") }), handler: async (p) => { const r = await unrealBridge.send("AiCreateBB", p); return r ? { success: true, message: `Blackboard created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const ueAiAddBBKey: ToolDefinition = { id: "ue_ai_add_bb_key", name: "Add Blackboard Key", description: "Add a key to a Blackboard asset", descriptionJa: "Blackboardアセットにキーを追加", category: "ue_ai", inputSchema: z.object({ bbName: z.string(), keyName: z.string(), keyType: z.enum(["Bool","Int","Float","String","Vector","Object","Enum","Class"]).default("Object") }), handler: async (p) => { const r = await unrealBridge.send("AiAddBBKey", p); return r ? { success: true, message: `Key ${p.keyName} added`, data: r } : { success: false, message: "Failed" }; } };

const ueAiAddBTTask: ToolDefinition = { id: "ue_ai_add_bt_task", name: "Add BT Task", description: "Add a task node to a Behavior Tree", descriptionJa: "Behavior Treeにタスクノードを追加", category: "ue_ai", inputSchema: z.object({ btName: z.string(), taskType: z.string(), parentNode: z.string().optional() }), handler: async (p) => { const r = await unrealBridge.send("AiAddBTTask", p); return r ? { success: true, message: `Task ${p.taskType} added`, data: r } : { success: false, message: "Failed" }; } };

const ueAiAddBTDecorator: ToolDefinition = { id: "ue_ai_add_bt_decorator", name: "Add BT Decorator", description: "Add a decorator to a Behavior Tree node", descriptionJa: "Behavior Treeノードにデコレーターを追加", category: "ue_ai", inputSchema: z.object({ btName: z.string(), decoratorType: z.string(), targetNode: z.string() }), handler: async (p) => { const r = await unrealBridge.send("AiAddBTDecorator", p); return r ? { success: true, message: `Decorator ${p.decoratorType} added`, data: r } : { success: false, message: "Failed" }; } };

const ueAiSetController: ToolDefinition = { id: "ue_ai_set_controller", name: "Set AI Controller", description: "Assign an AI Controller class to a pawn", descriptionJa: "PawnにAI Controllerクラスを割り当て", category: "ue_ai", inputSchema: z.object({ actorName: z.string(), controllerClass: z.string().default("AIController") }), handler: async (p) => { const r = await unrealBridge.send("AiSetController", p); return r ? { success: true, message: `AI Controller set on ${p.actorName}`, data: r } : { success: false, message: "Failed" }; } };

const ueAiRunBT: ToolDefinition = { id: "ue_ai_run_bt", name: "Run Behavior Tree", description: "Start running a Behavior Tree on an AI controller", descriptionJa: "AIコントローラーでBehavior Treeを実行開始", category: "ue_ai", inputSchema: z.object({ actorName: z.string(), btPath: z.string() }), handler: async (p) => { const r = await unrealBridge.send("AiRunBT", p); return r ? { success: true, message: `BT running on ${p.actorName}`, data: r } : { success: false, message: "Failed" }; } };

const ueAiAddEqs: ToolDefinition = { id: "ue_ai_add_eqs", name: "Create EQS Query", description: "Create an Environment Query System query", descriptionJa: "Environment Query System (EQS) クエリを作成", category: "ue_ai", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/AI"), generatorType: z.enum(["Grid","Circle","OnCircle","Cone","Donut"]).default("Grid") }), handler: async (p) => { const r = await unrealBridge.send("AiAddEqs", p); return r ? { success: true, message: `EQS created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

export const ueAiTools: ToolDefinition[] = [ ueAiCreateBT, ueAiCreateBB, ueAiAddBBKey, ueAiAddBTTask, ueAiAddBTDecorator, ueAiSetController, ueAiRunBT, ueAiAddEqs ];