import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { unrealBridge } from "../bridge/unreal-bridge";

const ueBuildSetPlatform: ToolDefinition = { id: "ue_build_set_platform", name: "Set Build Platform", description: "Set the target platform for packaging", descriptionJa: "パッケージングのターゲットプラットフォームを設定", category: "ue_build", inputSchema: z.object({ platform: z.enum(["Windows","Linux","Mac","Android","iOS","PS5","XboxSeriesX","Switch"]).default("Windows") }), handler: async (p) => { const r = await unrealBridge.send("BuildSetPlatform", p); return r ? { success: true, message: `Platform: ${p.platform}`, data: r } : { success: false, message: "Failed" }; } };

const ueBuildSetConfig: ToolDefinition = { id: "ue_build_set_config", name: "Set Build Configuration", description: "Set build configuration (Development, Shipping, etc.)", descriptionJa: "ビルド構成を設定（Development, Shipping等）", category: "ue_build", inputSchema: z.object({ config: z.enum(["Debug","DebugGame","Development","Test","Shipping"]).default("Development") }), handler: async (p) => { const r = await unrealBridge.send("BuildSetConfig", p); return r ? { success: true, message: `Config: ${p.config}`, data: r } : { success: false, message: "Failed" }; } };

const ueBuildPackage: ToolDefinition = { id: "ue_build_package", name: "Package Project", description: "Package the project for distribution", descriptionJa: "配布用にプロジェクトをパッケージ", category: "ue_build", inputSchema: z.object({ outputDir: z.string().default("./Package") }), handler: async (p) => { const r = await unrealBridge.send("BuildPackage", p); return r ? { success: true, message: "Packaging started", data: r } : { success: false, message: "Failed" }; } };

const ueBuildCook: ToolDefinition = { id: "ue_build_cook", name: "Cook Content", description: "Cook content for the target platform", descriptionJa: "ターゲットプラットフォーム用にコンテンツをクック", category: "ue_build", inputSchema: z.object({ platform: z.string().default("Windows"), iterative: z.boolean().default(true) }), handler: async (p) => { const r = await unrealBridge.send("BuildCook", p); return r ? { success: true, message: `Cooking for ${p.platform}`, data: r } : { success: false, message: "Failed" }; } };

const ueBuildLightmaps: ToolDefinition = { id: "ue_build_lightmaps", name: "Build Lightmaps", description: "Build lighting for the current level", descriptionJa: "現在のレベルのライティングをビルド", category: "ue_build", inputSchema: z.object({ quality: z.enum(["Preview","Medium","High","Production"]).default("High") }), handler: async (p) => { const r = await unrealBridge.send("BuildLightmaps", p); return r ? { success: true, message: `Building lighting: ${p.quality}`, data: r } : { success: false, message: "Failed" }; } };

const ueBuildGetStatus: ToolDefinition = { id: "ue_build_get_status", name: "Get Build Status", description: "Get current build/cook status and progress", descriptionJa: "現在のビルド/クック状態と進捗を取得", category: "ue_build", inputSchema: z.object({}), handler: async (p) => { const r = await unrealBridge.send("BuildGetStatus", p); return r ? { success: true, message: "Build status retrieved", data: r } : { success: false, message: "Failed" }; } };

export const ueBuildTools: ToolDefinition[] = [ ueBuildSetPlatform, ueBuildSetConfig, ueBuildPackage, ueBuildCook, ueBuildLightmaps, ueBuildGetStatus ];