import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const ueBuildSetPlatform: ToolDefinition = { id: "ue_build_set_platform", name: "Set Build Platform", description: "Set the target platform for packaging", descriptionJa: "パッケージングのターゲットプラットフォームを設定", category: "ue_build", inputSchema: z.object({ platform: z.enum(["Windows","Linux","Mac","Android","iOS","PS5","XboxSeriesX","Switch"]).default("Windows") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "BuildSetPlatform", p, { successMessage: (_, p) => `Platform: ${p.platform}` }) } };

const ueBuildSetConfig: ToolDefinition = { id: "ue_build_set_config", name: "Set Build Configuration", description: "Set build configuration (Development, Shipping, etc.)", descriptionJa: "ビルド構成を設定（Development, Shipping等）", category: "ue_build", inputSchema: z.object({ config: z.enum(["Debug","DebugGame","Development","Test","Shipping"]).default("Development") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "BuildSetConfig", p, { successMessage: (_, p) => `Config: ${p.config}` }) } };

const ueBuildPackage: ToolDefinition = { id: "ue_build_package", name: "Package Project", description: "Package the project for distribution", descriptionJa: "配布用にプロジェクトをパッケージ", category: "ue_build", inputSchema: z.object({ outputDir: z.string().default("./Package") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "BuildPackage", p, { successMessage: "Packaging started" }) } };

const ueBuildCook: ToolDefinition = { id: "ue_build_cook", name: "Cook Content", description: "Cook content for the target platform", descriptionJa: "ターゲットプラットフォーム用にコンテンツをクック", category: "ue_build", inputSchema: z.object({ platform: z.string().default("Windows"), iterative: z.boolean().default(true) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "BuildCook", p, { successMessage: (_, p) => `Cooking for ${p.platform}` }) } };

const ueBuildLightmaps: ToolDefinition = { id: "ue_build_lightmaps", name: "Build Lightmaps", description: "Build lighting for the current level", descriptionJa: "現在のレベルのライティングをビルド", category: "ue_build", inputSchema: z.object({ quality: z.enum(["Preview","Medium","High","Production"]).default("High") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "BuildLightmaps", p, { successMessage: (_, p) => `Building lighting: ${p.quality}` }) } };

const ueBuildGetStatus: ToolDefinition = { id: "ue_build_get_status", name: "Get Build Status", description: "Get current build/cook status and progress", descriptionJa: "現在のビルド/クック状態と進捗を取得", category: "ue_build", inputSchema: z.object({}), handler: async (p) => { return bridgeSendAsToolResult("unreal", "BuildGetStatus", p, { successMessage: "Build status retrieved" }) } };

export const ueBuildTools: ToolDefinition[] = [ ueBuildSetPlatform, ueBuildSetConfig, ueBuildPackage, ueBuildCook, ueBuildLightmaps, ueBuildGetStatus ];