import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const ueFoliageAddType: ToolDefinition = { id: "ue_foliage_add_type", name: "Add Foliage Type", description: "Add a static mesh as a foliage type", descriptionJa: "スタティックメッシュをフォリッジタイプとして追加", category: "ue_foliage", inputSchema: z.object({ meshPath: z.string(), density: z.number().default(100), minScale: z.number().default(0.8), maxScale: z.number().default(1.2) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "FoliageAddType", p, { successMessage: "Foliage type added" }) } };

const ueFoliagePaint: ToolDefinition = { id: "ue_foliage_paint", name: "Paint Foliage", description: "Paint foliage instances in an area", descriptionJa: "エリア内にフォリッジインスタンスをペイント", category: "ue_foliage", inputSchema: z.object({ meshPath: z.string(), x: z.number(), y: z.number(), radius: z.number().default(1000), count: z.number().default(50) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "FoliagePaint", p, { successMessage: (_, p) => `${p.count} foliage painted` }) } };

const ueFoliageErase: ToolDefinition = { id: "ue_foliage_erase", name: "Erase Foliage", description: "Erase foliage instances in an area", descriptionJa: "エリア内のフォリッジインスタンスを消去", category: "ue_foliage", inputSchema: z.object({ x: z.number(), y: z.number(), radius: z.number().default(500), meshPath: z.string().optional() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "FoliageErase", p, { successMessage: "Foliage erased" }) } };

const ueFoliageSetSettings: ToolDefinition = { id: "ue_foliage_set_settings", name: "Set Foliage Settings", description: "Configure foliage density, align to surface, random rotation", descriptionJa: "フォリッジの密度・表面整列・ランダム回転を設定", category: "ue_foliage", inputSchema: z.object({ meshPath: z.string(), alignToNormal: z.boolean().default(true), randomYaw: z.boolean().default(true), groundSlope: z.number().default(45), cullingDistance: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "FoliageSetSettings", p, { successMessage: "Foliage settings updated" }) } };

const ueFoliageConvertToStatic: ToolDefinition = { id: "ue_foliage_to_static", name: "Convert Foliage to Static", description: "Convert foliage instances to static mesh actors", descriptionJa: "フォリッジインスタンスをスタティックメッシュアクターに変換", category: "ue_foliage", inputSchema: z.object({ meshPath: z.string() }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "FoliageToStatic", p, { successMessage: "Foliage converted to static" }) } };

const ueFoliageGetInfo: ToolDefinition = { id: "ue_foliage_get_info", name: "Get Foliage Info", description: "Get foliage type count and instance statistics", descriptionJa: "フォリッジタイプ数とインスタンス統計を取得", category: "ue_foliage", inputSchema: z.object({}), handler: async (p) => { return bridgeSendAsToolResult("unreal", "FoliageGetInfo", p, { successMessage: "Foliage info retrieved" }) } };

export const ueFoliageTools: ToolDefinition[] = [ ueFoliageAddType, ueFoliagePaint, ueFoliageErase, ueFoliageSetSettings, ueFoliageConvertToStatic, ueFoliageGetInfo ];