import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
const ueLevelCreate: ToolDefinition = { id: "ue_level_create", name: "Create Level", description: "Create a new empty level", descriptionJa: "新しい空のレベルを作成", category: "ue_level", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/Maps"), template: z.enum(["Empty","Default","TimeOfDay","VR"]).default("Default") }), handler: async (p) => { const r = await bridge.send("unreal", "LevelCreate", p); return r ? { success: true, message: `Level created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const ueLevelOpen: ToolDefinition = { id: "ue_level_open", name: "Open Level", description: "Open an existing level in the editor", descriptionJa: "既存のレベルをエディタで開く", category: "ue_level", inputSchema: z.object({ levelPath: z.string() }), handler: async (p) => { const r = await bridge.send("unreal", "LevelOpen", p); return r ? { success: true, message: `Level opened: ${p.levelPath}`, data: r } : { success: false, message: "Failed" }; } };

const ueLevelSave: ToolDefinition = { id: "ue_level_save", name: "Save Level", description: "Save the current level", descriptionJa: "現在のレベルを保存", category: "ue_level", inputSchema: z.object({}), handler: async (p) => { const r = await bridge.send("unreal", "LevelSave", p); return r ? { success: true, message: "Level saved", data: r } : { success: false, message: "Failed" }; } };

const ueLevelAddSublevel: ToolDefinition = { id: "ue_level_add_sublevel", name: "Add Streaming Sublevel", description: "Add a streaming sublevel to the persistent level", descriptionJa: "パーシスタントレベルにストリーミングサブレベルを追加", category: "ue_level", inputSchema: z.object({ sublevelPath: z.string(), streamingMethod: z.enum(["AlwaysLoaded","Blueprint","LevelStreamingDynamic"]).default("Blueprint") }), handler: async (p) => { const r = await bridge.send("unreal", "LevelAddSublevel", p); return r ? { success: true, message: `Sublevel added: ${p.sublevelPath}`, data: r } : { success: false, message: "Failed" }; } };

const ueLevelSetGameMode: ToolDefinition = { id: "ue_level_set_gamemode", name: "Set Level Game Mode", description: "Override the GameMode for this level", descriptionJa: "このレベルのGameModeをオーバーライド", category: "ue_level", inputSchema: z.object({ gameModePath: z.string() }), handler: async (p) => { const r = await bridge.send("unreal", "LevelSetGameMode", p); return r ? { success: true, message: "GameMode set", data: r } : { success: false, message: "Failed" }; } };

const ueLevelGetInfo: ToolDefinition = { id: "ue_level_get_info", name: "Get Level Info", description: "Get actor count, sublevels, and world settings", descriptionJa: "アクター数・サブレベル・ワールド設定情報を取得", category: "ue_level", inputSchema: z.object({}), handler: async (p) => { const r = await bridge.send("unreal", "LevelGetInfo", p); return r ? { success: true, message: "Level info retrieved", data: r } : { success: false, message: "Failed" }; } };

export const ueLevelTools: ToolDefinition[] = [ ueLevelCreate, ueLevelOpen, ueLevelSave, ueLevelAddSublevel, ueLevelSetGameMode, ueLevelGetInfo ];