import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { unrealBridge } from "../bridge/unreal-bridge";

const ueMhSpawn: ToolDefinition = { id: "ue_mh_spawn", name: "Spawn MetaHuman", description: "Spawn a MetaHuman character in the level", descriptionJa: "レベルにMetaHumanキャラクターをスポーン", category: "ue_metahuman", inputSchema: z.object({ metahumanPath: z.string(), x: z.number().default(0), y: z.number().default(0), z: z.number().default(0), name: z.string().optional() }), handler: async (p) => { const r = await unrealBridge.send("MhSpawn", p); return r ? { success: true, message: "MetaHuman spawned", data: r } : { success: false, message: "Failed" }; } };

const ueMhSetBody: ToolDefinition = { id: "ue_mh_set_body", name: "Set MetaHuman Body", description: "Set body type and proportions of a MetaHuman", descriptionJa: "MetaHumanの体型とプロポーションを設定", category: "ue_metahuman", inputSchema: z.object({ actorName: z.string(), bodyType: z.enum(["Average","Athletic","Heavy","Thin"]).default("Average"), height: z.number().default(175) }), handler: async (p) => { const r = await unrealBridge.send("MhSetBody", p); return r ? { success: true, message: `Body set: ${p.bodyType}`, data: r } : { success: false, message: "Failed" }; } };

const ueMhSetFace: ToolDefinition = { id: "ue_mh_set_face", name: "Set MetaHuman Face", description: "Adjust facial features of a MetaHuman", descriptionJa: "MetaHumanの顔の特徴を調整", category: "ue_metahuman", inputSchema: z.object({ actorName: z.string(), preset: z.string().optional(), jawWidth: z.number().optional(), eyeSize: z.number().optional(), noseLength: z.number().optional() }), handler: async (p) => { const r = await unrealBridge.send("MhSetFace", p); return r ? { success: true, message: "Face adjusted", data: r } : { success: false, message: "Failed" }; } };

const ueMhSetClothing: ToolDefinition = { id: "ue_mh_set_clothing", name: "Set MetaHuman Clothing", description: "Assign clothing assets to a MetaHuman", descriptionJa: "MetaHumanに衣装アセットを割り当て", category: "ue_metahuman", inputSchema: z.object({ actorName: z.string(), topPath: z.string().optional(), bottomPath: z.string().optional(), shoesPath: z.string().optional() }), handler: async (p) => { const r = await unrealBridge.send("MhSetClothing", p); return r ? { success: true, message: "Clothing set", data: r } : { success: false, message: "Failed" }; } };

const ueMhSetAnimation: ToolDefinition = { id: "ue_mh_set_animation", name: "Set MetaHuman Animation", description: "Assign animation blueprint or play animation on MetaHuman", descriptionJa: "MetaHumanにアニメーションBPを割り当てまたは再生", category: "ue_metahuman", inputSchema: z.object({ actorName: z.string(), animBpPath: z.string().optional(), montagePath: z.string().optional() }), handler: async (p) => { const r = await unrealBridge.send("MhSetAnimation", p); return r ? { success: true, message: "Animation set", data: r } : { success: false, message: "Failed" }; } };

const ueMhSetLiveLink: ToolDefinition = { id: "ue_mh_set_livelink", name: "Set MetaHuman Live Link", description: "Enable Live Link facial/body capture on MetaHuman", descriptionJa: "MetaHumanでLive Linkフェイシャル/ボディキャプチャを有効化", category: "ue_metahuman", inputSchema: z.object({ actorName: z.string(), source: z.enum(["iPhone","Rokoko","OptiTrack","Vicon","Custom"]).default("iPhone"), facialCapture: z.boolean().default(true), bodyCapture: z.boolean().default(false) }), handler: async (p) => { const r = await unrealBridge.send("MhSetLiveLink", p); return r ? { success: true, message: `Live Link: ${p.source}`, data: r } : { success: false, message: "Failed" }; } };

export const ueMetaHumanTools: ToolDefinition[] = [ ueMhSpawn, ueMhSetBody, ueMhSetFace, ueMhSetClothing, ueMhSetAnimation, ueMhSetLiveLink ];