import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { unrealBridge } from "../bridge/unreal-bridge";

const uePcgCreateGraph: ToolDefinition = { id: "ue_pcg_create_graph", name: "Create PCG Graph", description: "Create a new PCG graph asset", descriptionJa: "新しいPCGグラフアセットを作成", category: "ue_pcg", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/PCG") }), handler: async (p) => { const r = await unrealBridge.send("PcgCreateGraph", p); return r ? { success: true, message: `PCG graph created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const uePcgAddNode: ToolDefinition = { id: "ue_pcg_add_node", name: "Add PCG Node", description: "Add a node to a PCG graph (Surface Sampler, Mesh Spawner, etc.)", descriptionJa: "PCGグラフにノードを追加（Surface Sampler, Mesh Spawner等）", category: "ue_pcg", inputSchema: z.object({ graphName: z.string(), nodeType: z.enum(["SurfaceSampler","MeshSpawner","PointFilter","DensityFilter","Transform","Bounds","Difference","Union","Intersection","Subgraph"]).default("SurfaceSampler") }), handler: async (p) => { const r = await unrealBridge.send("PcgAddNode", p); return r ? { success: true, message: `Node ${p.nodeType} added`, data: r } : { success: false, message: "Failed" }; } };

const uePcgConnectNodes: ToolDefinition = { id: "ue_pcg_connect_nodes", name: "Connect PCG Nodes", description: "Connect two nodes in a PCG graph", descriptionJa: "PCGグラフ内の2つのノードを接続", category: "ue_pcg", inputSchema: z.object({ graphName: z.string(), fromNode: z.string(), fromPin: z.string(), toNode: z.string(), toPin: z.string() }), handler: async (p) => { const r = await unrealBridge.send("PcgConnectNodes", p); return r ? { success: true, message: `Connected ${p.fromNode} -> ${p.toNode}`, data: r } : { success: false, message: "Failed" }; } };

const uePcgSetParam: ToolDefinition = { id: "ue_pcg_set_param", name: "Set PCG Parameter", description: "Set a parameter on a PCG node", descriptionJa: "PCGノードのパラメータを設定", category: "ue_pcg", inputSchema: z.object({ graphName: z.string(), nodeName: z.string(), paramName: z.string(), value: z.any() }), handler: async (p) => { const r = await unrealBridge.send("PcgSetParam", p); return r ? { success: true, message: `Param ${p.paramName} set`, data: r } : { success: false, message: "Failed" }; } };

const uePcgExecute: ToolDefinition = { id: "ue_pcg_execute", name: "Execute PCG Graph", description: "Generate content by executing a PCG graph on an actor", descriptionJa: "アクター上でPCGグラフを実行してコンテンツを生成", category: "ue_pcg", inputSchema: z.object({ actorName: z.string(), graphPath: z.string() }), handler: async (p) => { const r = await unrealBridge.send("PcgExecute", p); return r ? { success: true, message: "PCG executed", data: r } : { success: false, message: "Failed" }; } };

const uePcgAddVolume: ToolDefinition = { id: "ue_pcg_add_volume", name: "Add PCG Volume", description: "Spawn a PCG Volume actor with a graph assigned", descriptionJa: "グラフを割り当てたPCG Volumeアクターをスポーン", category: "ue_pcg", inputSchema: z.object({ graphPath: z.string(), x: z.number().default(0), y: z.number().default(0), z: z.number().default(0), extentX: z.number().default(5000), extentY: z.number().default(5000), extentZ: z.number().default(1000) }), handler: async (p) => { const r = await unrealBridge.send("PcgAddVolume", p); return r ? { success: true, message: "PCG Volume added", data: r } : { success: false, message: "Failed" }; } };

export const uePcgTools: ToolDefinition[] = [ uePcgCreateGraph, uePcgAddNode, uePcgConnectNodes, uePcgSetParam, uePcgExecute, uePcgAddVolume ];