import { ToolDefinition } from "../core/registry";
import { bridgeSendAsToolResult } from "../core/bridgeToolResult";
import { z } from "zod";
const uePhysicsEnable: ToolDefinition = { id: "ue_physics_enable", name: "Enable Physics", description: "Enable physics simulation on an actor", descriptionJa: "アクターの物理シミュレーションを有効化", category: "ue_physics", inputSchema: z.object({ actorName: z.string(), simulate: z.boolean().default(true), gravity: z.boolean().default(true) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "PhysicsEnable", p, { successMessage: (_, p) => `Physics ${p.simulate ? "enabled" : "disabled"} on ${p.actorName}` }) } };

const uePhysicsSetMass: ToolDefinition = { id: "ue_physics_set_mass", name: "Set Mass", description: "Set the mass of a physics-enabled actor in kg", descriptionJa: "物理有効アクターの質量をkgで設定", category: "ue_physics", inputSchema: z.object({ actorName: z.string(), mass: z.number().default(100) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "PhysicsSetMass", p, { successMessage: (_, p) => `Mass set to ${p.mass}kg` }) } };

const uePhysicsAddForce: ToolDefinition = { id: "ue_physics_add_force", name: "Add Force", description: "Apply a force to a physics actor", descriptionJa: "物理アクターに力を加える", category: "ue_physics", inputSchema: z.object({ actorName: z.string(), forceX: z.number(), forceY: z.number(), forceZ: z.number(), impulse: z.boolean().default(false) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "PhysicsAddForce", p, { successMessage: (_, p) => `Force applied to ${p.actorName}` }) } };

const uePhysicsSetDamping: ToolDefinition = { id: "ue_physics_set_damping", name: "Set Damping", description: "Set linear and angular damping", descriptionJa: "リニア・アンギュラーダンピングを設定", category: "ue_physics", inputSchema: z.object({ actorName: z.string(), linearDamping: z.number().default(0.01), angularDamping: z.number().default(0) }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "PhysicsSetDamping", p, { successMessage: (_, p) => `Damping set on ${p.actorName}` }) } };

const uePhysicsAddConstraint: ToolDefinition = { id: "ue_physics_add_constraint", name: "Add Physics Constraint", description: "Add a physics constraint between two actors", descriptionJa: "2つのアクター間に物理コンストレイントを追加", category: "ue_physics", inputSchema: z.object({ actor1: z.string(), actor2: z.string(), constraintType: z.enum(["Fixed","Hinge","Prismatic","BallSocket"]).default("Hinge") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "PhysicsAddConstraint", p, { successMessage: (_, p) => `Constraint ${p.constraintType} added` }) } };

const uePhysicsSetCollisionProfile: ToolDefinition = { id: "ue_physics_set_collision_profile", name: "Set Collision Profile", description: "Set the collision preset profile on an actor", descriptionJa: "アクターのコリジョンプリセットプロファイルを設定", category: "ue_physics", inputSchema: z.object({ actorName: z.string(), profile: z.enum(["NoCollision","BlockAll","OverlapAll","BlockAllDynamic","OverlapAllDynamic","Pawn","PhysicsActor","Trigger"]).default("BlockAllDynamic") }), handler: async (p) => { return bridgeSendAsToolResult("unreal", "PhysicsSetCollisionProfile", p, { successMessage: (_, p) => `Profile set: ${p.profile}` }) } };

export const uePhysicsTools: ToolDefinition[] = [ uePhysicsEnable, uePhysicsSetMass, uePhysicsAddForce, uePhysicsSetDamping, uePhysicsAddConstraint, uePhysicsSetCollisionProfile ];