import { ToolDefinition } from "../core/registry";
import { z } from "zod";
import { unrealBridge } from "../bridge/unreal-bridge";

const ueSeqCreate: ToolDefinition = { id: "ue_seq_create", name: "Create Level Sequence", description: "Create a new Level Sequence asset", descriptionJa: "新しいLevel Sequenceアセットを作成", category: "ue_sequencer", inputSchema: z.object({ name: z.string(), path: z.string().default("/Game/Cinematics") }), handler: async (p) => { const r = await unrealBridge.send("SeqCreate", p); return r ? { success: true, message: `Sequence created: ${p.name}`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqAddTrack: ToolDefinition = { id: "ue_seq_add_track", name: "Add Sequencer Track", description: "Add a track (Transform, Animation, Camera, Audio, Event) to a sequence", descriptionJa: "シーケンスにトラック（Transform, Animation等）を追加", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string(), actorName: z.string(), trackType: z.enum(["Transform","Animation","CameraCut","Audio","Event","Fade","Material"]).default("Transform") }), handler: async (p) => { const r = await unrealBridge.send("SeqAddTrack", p); return r ? { success: true, message: `Track ${p.trackType} added`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqAddKeyframe: ToolDefinition = { id: "ue_seq_add_keyframe", name: "Add Keyframe", description: "Add a keyframe to a sequencer track at a specific time", descriptionJa: "指定時間にシーケンサートラックへキーフレームを追加", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string(), actorName: z.string(), trackType: z.string(), time: z.number(), value: z.any() }), handler: async (p) => { const r = await unrealBridge.send("SeqAddKeyframe", p); return r ? { success: true, message: `Keyframe added at ${p.time}s`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqSetDuration: ToolDefinition = { id: "ue_seq_set_duration", name: "Set Sequence Duration", description: "Set the playback range duration of a sequence", descriptionJa: "シーケンスの再生範囲の長さを設定", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string(), duration: z.number().default(10) }), handler: async (p) => { const r = await unrealBridge.send("SeqSetDuration", p); return r ? { success: true, message: `Duration set to ${p.duration}s`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqPlay: ToolDefinition = { id: "ue_seq_play", name: "Play Sequence", description: "Play a Level Sequence in the editor viewport", descriptionJa: "エディタビューポートでLevel Sequenceを再生", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string(), loop: z.boolean().default(false) }), handler: async (p) => { const r = await unrealBridge.send("SeqPlay", p); return r ? { success: true, message: `Playing: ${p.sequenceName}`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqAddCameraCut: ToolDefinition = { id: "ue_seq_add_camera_cut", name: "Add Camera Cut", description: "Add a camera cut track binding a camera actor", descriptionJa: "カメラアクターをバインドするカメラカットトラックを追加", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string(), cameraName: z.string(), startTime: z.number().default(0), endTime: z.number().default(5) }), handler: async (p) => { const r = await unrealBridge.send("SeqAddCameraCut", p); return r ? { success: true, message: `Camera cut added: ${p.cameraName}`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqRenderMovie: ToolDefinition = { id: "ue_seq_render_movie", name: "Render Movie", description: "Render the sequence to a video file", descriptionJa: "シーケンスをビデオファイルにレンダリング", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string(), outputDir: z.string().default("./Renders"), resolution: z.enum(["720p","1080p","2160p"]).default("1080p"), format: z.enum(["AVI","MP4","PNG"]).default("MP4") }), handler: async (p) => { const r = await unrealBridge.send("SeqRenderMovie", p); return r ? { success: true, message: `Rendering: ${p.resolution} ${p.format}`, data: r } : { success: false, message: "Failed" }; } };

const ueSeqGetInfo: ToolDefinition = { id: "ue_seq_get_info", name: "Get Sequence Info", description: "Get tracks, duration, and bindings of a sequence", descriptionJa: "シーケンスのトラック・長さ・バインディング情報を取得", category: "ue_sequencer", inputSchema: z.object({ sequenceName: z.string() }), handler: async (p) => { const r = await unrealBridge.send("SeqGetInfo", p); return r ? { success: true, message: `Info for ${p.sequenceName}`, data: r } : { success: false, message: "Failed" }; } };

export const ueSequencerTools: ToolDefinition[] = [ ueSeqCreate, ueSeqAddTrack, ueSeqAddKeyframe, ueSeqSetDuration, ueSeqPlay, ueSeqAddCameraCut, ueSeqRenderMovie, ueSeqGetInfo ];