import { ToolDefinition } from "../core/registry";
import { bridge } from "../bridge";
import { z } from "zod";
export const unityVrchatTools: ToolDefinition[] = [
  {
    id: "unity_vrc_setup_avatar",
    name: "VRChat: Setup Avatar Descriptor",
    description: "Auto-configure VRC Avatar Descriptor on a humanoid model: set viewpoint, lip sync mode, eye look, and playable layers.",
    descriptionJa: "VRCアバターディスクリプター自動設定（ビューポイント・リップシンクモード・アイルック・Playableレイヤーを自動構成）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      viewpointOffset: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional().describe("Viewpoint position offset (default auto-calculated from head bone)"),
      lipSyncMode: z.enum(["viseme_blend_shapes", "jaw_flap_bone", "jaw_flap_blend_shape"]).optional().describe("Lip sync mode (default viseme_blend_shapes)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_setup_avatar", params),
  },
  {
    id: "unity_vrc_add_physbone",
    name: "VRChat: Add PhysBone",
    description: "Add a VRC PhysBone component to a bone chain with stiffness, gravity, pull, spring, and collision settings.",
    descriptionJa: "PhysBoneコンポーネント追加（対象ボーンチェーンに剛性・重力・プル・スプリング・コリジョン設定）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      rootBone: z.string().describe("PhysBone root bone name (e.g. Hair_Root, Skirt_Root)"),
      pull: z.number().min(0).max(1).optional().describe("Pull force (default 0.2)"),
      spring: z.number().min(0).max(1).optional().describe("Spring force (default 0.2)"),
      stiffness: z.number().min(0).max(1).optional().describe("Stiffness (default 0.2)"),
      gravity: z.number().min(-1).max(1).optional().describe("Gravity (-1 to 1, default 0.1)"),
      gravityFalloff: z.number().min(0).max(1).optional().describe("Gravity falloff (default 0.5)"),
      radius: z.number().optional().describe("Collision radius (default 0.02)"),
      allowGrabbing: z.boolean().optional().describe("Allow grabbing (default true)"),
      allowPosing: z.boolean().optional().describe("Allow posing (default true)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_add_physbone", params),
  },
  {
    id: "unity_vrc_batch_physbone",
    name: "VRChat: Batch PhysBone Setup",
    description: "Batch configure PhysBones for multiple bone chains at once (hair, skirt, tail, accessories). Provide an array of chain configs.",
    descriptionJa: "PhysBone一括設定（髪・スカート・尻尾・アクセサリの複数チェーンをまとめて構成）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      chains: z.array(z.object({
        rootBone: z.string().describe("Chain root bone name"),
        pull: z.number().min(0).max(1).optional(),
        spring: z.number().min(0).max(1).optional(),
        stiffness: z.number().min(0).max(1).optional(),
        gravity: z.number().min(-1).max(1).optional(),
        radius: z.number().optional(),
      })).describe("Array of PhysBone chain configurations"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_batch_physbone", params),
  },
  {
    id: "unity_vrc_setup_expressions",
    name: "VRChat: Setup Expression Menu & Parameters",
    description: "Auto-generate VRC Expression Menu and Parameters assets with common toggles, radials, and sub-menus.",
    descriptionJa: "Expression Menu＋Parametersを自動生成（一般的なトグル・ラジアル・サブメニュー付きテンプレート）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      template: z.enum(["basic", "full", "minimal"]).optional().describe("Template complexity (default basic)"),
      customToggles: z.array(z.string()).optional().describe("Custom toggle names to include (e.g. Hat, Jacket, Glasses)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_setup_expressions", params),
  },
  {
    id: "unity_vrc_add_toggle",
    name: "VRChat: Add Clothing/Accessory Toggle",
    description: "Add a toggle to the Expression Menu for a specific clothing item or accessory (shows/hides a GameObject, synced across network).",
    descriptionJa: "衣装/アクセサリトグル追加（Expression Menuに項目追加、GameObjectの表示切替、ネットワーク同期）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      toggleTarget: z.string().describe("GameObject path to toggle (e.g. Armature/Hips/Spine/Chest/Jacket)"),
      menuName: z.string().describe("Display name in expression menu"),
      defaultOn: z.boolean().optional().describe("Default state on (default true)"),
      icon: z.string().optional().describe("Icon texture path (optional)"),
      saved: z.boolean().optional().describe("Save toggle state between sessions (default true)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_add_toggle", params),
  },
  {
    id: "unity_vrc_set_viseme",
    name: "VRChat: Set Viseme Configuration",
    description: "Configure viseme blend shapes on the Avatar Descriptor. Auto-maps if blend shape names follow VRChat convention.",
    descriptionJa: "Viseme設定（Avatar Descriptorのブレンドシェイプマッピング。VRChat命名規則準拠なら自動マッピング）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      autoMap: z.boolean().optional().describe("Auto-map visemes by naming convention (default true)"),
      customMapping: z.record(z.string()).optional().describe("Custom viseme-to-blendshape mapping overrides"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_set_viseme", params),
  },
  {
    id: "unity_vrc_set_eye_tracking",
    name: "VRChat: Set Eye Tracking",
    description: "Configure eye tracking: set eye bone references, rotation ranges, and eyelid blend shapes for blink.",
    descriptionJa: "アイトラッキング設定（アイボーン指定・回転範囲・まばたき用ブレンドシェイプ設定）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      leftEyeBone: z.string().optional().describe("Left eye bone name (auto-detected if standard naming)"),
      rightEyeBone: z.string().optional().describe("Right eye bone name (auto-detected if standard naming)"),
      rotationRangeUp: z.number().optional().describe("Max upward rotation degrees (default 15)"),
      rotationRangeDown: z.number().optional().describe("Max downward rotation degrees (default 12)"),
      rotationRangeHorizontal: z.number().optional().describe("Max horizontal rotation degrees (default 18)"),
      blinkBlendShape: z.string().optional().describe("Blink blend shape name (auto-detected if possible)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_set_eye_tracking", params),
  },
  {
    id: "unity_vrc_set_bounding_box",
    name: "VRChat: Set Bounding Box",
    description: "Auto-calculate or manually set the avatar bounding box for culling. Ensures avatar is visible from expected distances.",
    descriptionJa: "バウンディングボックス設定（自動計算 or 手動設定。適切な表示距離でのカリングを保証）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      mode: z.enum(["auto", "manual"]).optional().describe("Calculation mode (default auto)"),
      manualSize: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional().describe("Manual bounding box size (if mode is manual)"),
      manualCenter: z.object({ x: z.number(), y: z.number(), z: z.number() }).optional().describe("Manual bounding box center offset"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_set_bounding_box", params),
  },
  {
    id: "unity_vrc_validate",
    name: "VRChat: Validate Avatar",
    description: "Run full VRChat avatar validation: performance rank (Excellent/Good/Medium/Poor/Very Poor), component checks, and actionable fix suggestions.",
    descriptionJa: "VRChatアバターバリデーション（パフォーマンスランク判定・コンポーネントチェック・修正提案付き）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      targetRank: z.enum(["excellent", "good", "medium", "poor"]).optional().describe("Target rank to validate against (default good)"),
      autoFix: z.boolean().optional().describe("Attempt auto-fix for simple issues (default false)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_validate", params),
  },
  {
    id: "unity_vrc_setup_fallback",
    name: "VRChat: Setup Fallback Avatar",
    description: "Configure fallback avatar settings for users who cannot display the full avatar (Safety/Performance blocking).",
    descriptionJa: "フォールバックアバター設定（Safety/Performanceブロック時の代替表示設定）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      fallbackType: z.enum(["generic", "slim", "impostor"]).optional().describe("Fallback type (default generic)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_setup_fallback", params),
  },
  {
    id: "unity_vrc_setup_face_tracking",
    name: "VRChat: Setup Face Tracking",
    description: "Configure Unified Expressions face tracking: map 70+ blend shapes to animator parameters, create FX layer with direct blend trees.",
    descriptionJa: "フェイストラッキング設定（Unified Expressions 70+ブレンドシェイプをAnimatorパラメータにマッピング、FXレイヤーにDirect BlendTree生成）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      autoMap: z.boolean().optional().describe("Auto-map by blend shape naming convention (default true)"),
      binaryParameters: z.boolean().optional().describe("Use binary parameters for optimization (default false)"),
      customMapping: z.record(z.string()).optional().describe("Custom expression-to-blendshape mapping overrides"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_setup_face_tracking", params),
  },
  {
    id: "unity_vrc_upload_prep",
    name: "VRChat: Upload Preparation",
    description: "Final pre-upload checklist: verify descriptor, validate performance rank, check thumbnail, set blueprint ID, and prepare build.",
    descriptionJa: "アップロード前最終準備（ディスクリプター確認・パフォーマンスランク検証・サムネイルチェック・BlueprintID設定・ビルド準備）",
    category: "Unity_VRChat",
    inputSchema: z.object({
      gameObjectName: z.string().describe("Target avatar root GameObject name"),
      avatarName: z.string().optional().describe("Avatar display name for VRChat"),
      description: z.string().optional().describe("Avatar description"),
      tags: z.array(z.string()).optional().describe("Tags for avatar search"),
      releaseStatus: z.enum(["public", "private"]).optional().describe("Release visibility (default private)"),
    }),
    handler: async (params) => bridge.send("unity", "unity_vrc_upload_prep", params),
  },
];